CREATE OR ALTER FUNCTION viz.TicksLog(@DomainMin float,@DomainMax float)
RETURNS TABLE AS RETURN
WITH bounds AS (SELECT CEILING(LOG10(NULLIF(CASE WHEN @DomainMin>0 THEN @DomainMin END,0))) Lo,
 FLOOR(LOG10(NULLIF(CASE WHEN @DomainMax>0 THEN @DomainMax END,0))) Hi
 WHERE @DomainMin>0 AND @DomainMin<@DomainMax AND @DomainMax<=1e16 AND @DomainMin>=1e-300),
p AS (SELECT DISTINCT CONVERT(int,Lo+FLOOR(N*(Hi-Lo)/CASE WHEN Hi-Lo<11 THEN NULLIF(Hi-Lo,0) ELSE 11 END)) E
 FROM bounds CROSS JOIN viz.Numbers(12) WHERE Hi>=Lo AND N<=Hi-Lo),
t AS (SELECT POWER(CONVERT(float,10),E) Value FROM p WHERE E IS NOT NULL),
r AS (SELECT Value FROM t WHERE (SELECT COUNT(*) FROM t)>=2
 UNION ALL SELECT @DomainMin FROM bounds WHERE (SELECT COUNT(*) FROM t)<2
 UNION ALL SELECT @DomainMax FROM bounds WHERE (SELECT COUNT(*) FROM t)<2)
SELECT CONVERT(int,ROW_NUMBER() OVER(ORDER BY Value)-1) TickOrder,Value FROM r;
