-- Generated by tools/build.ps1. Execute the complete script in the selected user database.
-- One batch: nested DDL is compiled inside the transaction and caught on failure.
SET NOCOUNT ON;
SET XACT_ABORT ON;
IF @@TRANCOUNT<>0 THROW 51001,'Run the installer outside an existing transaction.',1;
IF DB_ID()<=4 THROW 51001,'Install into a user database.',1;
IF CONVERT(int,SERVERPROPERTY('ProductMajorVersion'))<14 OR
   (SELECT compatibility_level FROM sys.databases WHERE database_id=DB_ID())<140
    THROW 51001,'Core requires SQL Server 2017 and compatibility level 140 or newer.',1;
DECLARE @Expected TABLE(Name sysname COLLATE Latin1_General_100_BIN2 PRIMARY KEY,Kind varchar(12),SourceHash varchar(64));
INSERT @Expected VALUES(N'CategoryValue_v1',N'TYPE','81408D7BC4199FD89CE7CB612AEF1698949F1F54679BB6B56199F8ACB3C2675F');
INSERT @Expected VALUES(N'XY_v1',N'TYPE','DB57BD33C869ABD9C5A17A2D62E0C48CE5486F46882E24AFF977E99E031FEE10');
INSERT @Expected VALUES(N'Vertex_v1',N'TYPE','39E0CA9C8CDDAF0B1DADD8DA683BE13617463C9757E1459C6F06A22D0B904F2E');
INSERT @Expected VALUES(N'Scene_v1',N'TYPE','5AE859211FA655466E779B3B75C543771C9B57ED932EC8969064A20FC20880BC');
INSERT @Expected VALUES(N'LibraryVersion',N'TABLE','3F9702A6D4A7E9AB15ED5D7CFAD516228C6470A225C2797FFA6DFB0A7D438DF4');
INSERT @Expected VALUES(N'ObjectManifest',N'TABLE','CDA88ADC2AE94E4EF8BDABD7F8DDBC9879A93418763BF78952F1B7784DE2EDF9');
INSERT @Expected VALUES(N'GlyphStroke',N'TABLE','119EF745C3A2D35F84A09FE084BDC86CBA96EF499FAAEAF2A44D3C7C0224E980');
INSERT @Expected VALUES(N'Numbers',N'TVF','85D6007A495280A4A8E8CD42063394D4E5E6D6EAAA66EA36F554DADC614A2363');
INSERT @Expected VALUES(N'Point',N'FUNCTION','DD124CBD9BC9B0B49AB9A95A978FEDC16836EB016D1A5B58556C94BF7BE66E53');
INSERT @Expected VALUES(N'CoordinateText',N'FUNCTION','67B32A9E6D6CA2D6B931A93379C7C2172C68F9AFA1E08E30C1633593813D6DED');
INSERT @Expected VALUES(N'Segment',N'FUNCTION','56EAC3CE8953A70573B20B7F47BA187EF223C99866E5DB16F91F341004168FF5');
INSERT @Expected VALUES(N'Rect',N'FUNCTION','3B876AB407BF86FA62F779C75303C2BDD6708209578F1667938BB31514D0E7D4');
INSERT @Expected VALUES(N'Circle',N'FUNCTION','A3DC2703637B20F7869B4B7F5621BC231B7D2DBE5BD19A4837B9E9F5A2230C93');
INSERT @Expected VALUES(N'Polyline',N'FUNCTION','A3AE8496FDD1DEE9D274020308E5ADE4677460CA9CDFC5B8DC644A5D4A808135');
INSERT @Expected VALUES(N'Polygon',N'FUNCTION','087ACCBE7E4182AF5B061F0C24982F1D00990FB17A4EC0B59886D503477EB413');
INSERT @Expected VALUES(N'ScaleLinear',N'FUNCTION','0B6E6ADB765EF8733F851EF1419870DE41E894B499A3577FC7CB5416826F171C');
INSERT @Expected VALUES(N'ScaleLog',N'FUNCTION','7A51BC9EB75C6BD8DCDC3E0D273372B80DA616961586A70F5822343FFFFF7823');
INSERT @Expected VALUES(N'ScaleBand',N'TVF','F2E72764C7AD4DE22364450CE72363E0B2EBCCCEA21262E61438920A7DBFAB6E');
INSERT @Expected VALUES(N'BubbleRadius',N'FUNCTION','625D150314558EF847C8A124949BE7AEDABE6B0EF8190ABA16FEAA0DD05E478F');
INSERT @Expected VALUES(N'TimeToEpoch',N'FUNCTION','15A9A193FEE2CD2509F1EE2074A3C60DC71BEBB3C838A4F3B0C83919F084E0A9');
INSERT @Expected VALUES(N'EpochToTime',N'FUNCTION','D997F12C22FF9E858A7DC9F1417032045C57A046C8042575E56DE58700C5F226');
INSERT @Expected VALUES(N'TickStep',N'FUNCTION','45D0472648E4D6A075008C65DB6A3F39B893533C862C1F961BEB96EABB10D92F');
INSERT @Expected VALUES(N'TicksLinear',N'TVF','A7C2D1449ADB27D1F9300ECD8165A65BE9F9DB2266E8BBE7738BFAA76F9DA552');
INSERT @Expected VALUES(N'NiceDomain',N'TVF','5054A8C59FB347D57EA0320CF29C9AD7ED499D05BE1403023E0C1600AB99EF01');
INSERT @Expected VALUES(N'TicksLog',N'TVF','68D90E4D8219EBF2B1A1384768AE02FE9783D8CCCBE0189AA9588324DAA496BB');
INSERT @Expected VALUES(N'TicksTime',N'TVF','0D5B686A4F82085B21215EE59E01790FEA3BAB9CD9A21C6B051C626251F2B9E1');
INSERT @Expected VALUES(N'RenderScene',N'PROCEDURE','2EC15920F06F5355199D78CDF3533E318439F03AA5ECE8A9C1F27505C32E9375');
BEGIN TRY
    BEGIN TRANSACTION;
    DECLARE @Lock int;
    EXEC @Lock=sys.sp_getapplock @Resource=N'TSQLViz.Core.Install',@LockMode='Exclusive',@LockOwner='Transaction',@LockTimeout=10000;
    IF @Lock<0 THROW 51001,'Could not acquire the Core installation lock.',1;
    DECLARE @Existing TABLE(Name sysname COLLATE Latin1_General_100_BIN2,Kind varchar(12),Id int,Class int);
    INSERT @Existing SELECT name,CASE type WHEN 'U' THEN 'TABLE' WHEN 'FN' THEN 'FUNCTION' WHEN 'FS' THEN 'FUNCTION' WHEN 'IF' THEN 'TVF' WHEN 'TF' THEN 'TVF' WHEN 'P' THEN 'PROCEDURE' ELSE type END,object_id,1
    FROM sys.objects WHERE schema_id=SCHEMA_ID('viz') AND parent_object_id=0 AND type<>'TT';
    INSERT @Existing SELECT name,'TYPE',user_type_id,6 FROM sys.types WHERE schema_id=SCHEMA_ID('viz') AND is_user_defined=1;
    DECLARE @Collision nvarchar(2048);
    SELECT @Collision=LEFT(STRING_AGG(CONVERT(nvarchar(max),x.Name),N', '),1900)
    FROM @Existing x LEFT JOIN @Expected e ON x.Name=e.Name AND x.Kind=e.Kind
    WHERE e.Name IS NULL OR NOT EXISTS(SELECT 1 FROM sys.extended_properties p WHERE p.class=x.Class AND p.major_id=x.Id AND p.minor_id=0 AND p.name=N'TSQLViz.Owner' AND CONVERT(nvarchar(100),p.value)=N'core-v1');
    IF @Collision IS NOT NULL BEGIN
        SET @Collision=N'Foreign or incompatible objects in viz: '+@Collision;
        THROW 51001,@Collision,1;
    END;
    IF SCHEMA_ID('viz') IS NOT NULL AND (SELECT principal_id FROM sys.schemas WHERE name='viz')<>DATABASE_PRINCIPAL_ID('dbo')
        THROW 51001,'The viz schema must be owned by dbo for the tested ownership chain.',1;
    IF EXISTS(SELECT 1 FROM @Existing) AND OBJECT_ID('viz.ObjectManifest','U') IS NULL
        THROW 51001,'Existing Core objects have no installation manifest.',1;
    IF DATABASE_PRINCIPAL_ID('viz_user') IS NOT NULL BEGIN
        IF OBJECT_ID('viz.ObjectManifest','U') IS NULL THROW 51001,'Foreign principal viz_user.',1;
        EXEC sys.sp_executesql N'IF NOT EXISTS(SELECT 1 FROM viz.ObjectManifest WHERE ObjectName=N''@role:viz_user'' AND ObjectKind=''ROLE'') THROW 51001,''Foreign principal viz_user.'',1;';
        IF NOT EXISTS(SELECT 1 FROM sys.database_principals WHERE name='viz_user' AND type='R' AND owning_principal_id=DATABASE_PRINCIPAL_ID('dbo'))
            THROW 51001,'Incompatible viz_user role.',1;
    END;
    -- Structural signatures protect immutable types and persisted tables from silent drift.
    DECLARE @Name sysname,@Kind varchar(12),@CatalogId int,@CatalogHash varbinary(32),@StoredHash varbinary(32),@Shape nvarchar(max),@InstalledSource varchar(64),@ExpectedSource varchar(64);
    DECLARE check_objects CURSOR LOCAL FAST_FORWARD FOR SELECT Name,Kind FROM @Existing WHERE Kind IN ('TYPE','TABLE');
    OPEN check_objects;
    FETCH NEXT FROM check_objects INTO @Name,@Kind;
    WHILE @@FETCH_STATUS=0 BEGIN
        SET @CatalogId=CASE WHEN @Kind='TYPE' THEN (SELECT type_table_object_id FROM sys.table_types WHERE schema_id=SCHEMA_ID('viz') AND name=@Name) ELSE OBJECT_ID(N'viz.'+QUOTENAME(@Name)) END;
        SET @Shape=(SELECT column_id,name,system_type_id,user_type_id,max_length,precision,scale,collation_name,is_nullable,is_identity FROM sys.columns WHERE object_id=@CatalogId ORDER BY column_id FOR XML RAW);
        SET @Shape=@Shape+(SELECT i.index_id,i.is_unique,i.is_primary_key,c.column_id,c.key_ordinal,c.is_descending_key FROM sys.indexes i JOIN sys.index_columns c ON c.object_id=i.object_id AND c.index_id=i.index_id WHERE i.object_id=@CatalogId ORDER BY i.index_id,c.index_column_id FOR XML RAW);
        SET @Shape=@Shape+COALESCE((SELECT definition FROM sys.check_constraints WHERE parent_object_id=@CatalogId ORDER BY definition FOR XML RAW),N'');
        SET @CatalogHash=HASHBYTES('SHA2_256',@Shape); SET @StoredHash=NULL;
        EXEC sys.sp_executesql N'SELECT @h=CatalogHash FROM viz.ObjectManifest WHERE ObjectName=@n;',N'@n sysname,@h varbinary(32) OUTPUT',@Name,@StoredHash OUTPUT;
        IF @StoredHash IS NULL OR @StoredHash<>@CatalogHash THROW 51001,'Core table/type structure differs from the installed manifest.',1;
        SET @InstalledSource=NULL;
        SELECT @ExpectedSource=SourceHash FROM @Expected WHERE Name=@Name;
        EXEC sys.sp_executesql N'SELECT @s=SourceHash FROM viz.ObjectManifest WHERE ObjectName=@n;',N'@n sysname,@s varchar(64) OUTPUT',@Name,@InstalledSource OUTPUT;
        IF @InstalledSource IS NULL OR @InstalledSource<>@ExpectedSource THROW 51001,'Changed table/type source requires an explicit versioned migration.',1;
        FETCH NEXT FROM check_objects INTO @Name,@Kind;
    END;
    CLOSE check_objects; DEALLOCATE check_objects;
    IF SCHEMA_ID('viz') IS NULL EXEC(N'CREATE SCHEMA viz AUTHORIZATION dbo;');
IF OBJECT_ID('viz.LibraryVersion','U') IS NOT NULL EXEC(N'IF EXISTS(SELECT 1 FROM viz.LibraryVersion WHERE Version<>''0.1.0-s2'') THROW 51001,''This installer supports clean install or same-version reinstall only.'',1;');
-- src/core/types/CategoryValue_v1.sql
IF TYPE_ID(N'viz.CategoryValue_v1') IS NULL EXEC sys.sp_executesql N'CREATE TYPE viz.[CategoryValue_v1] AS TABLE (
    ItemKey nvarchar(200) COLLATE Latin1_General_100_BIN2 NOT NULL PRIMARY KEY,
    CategoryKey nvarchar(200) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CategoryLabel nvarchar(400) NOT NULL,
    CategoryOrder int NOT NULL,
    SeriesKey nvarchar(200) COLLATE Latin1_General_100_BIN2 NOT NULL,
    SeriesLabel nvarchar(400) NOT NULL,
    SeriesOrder int NOT NULL,
    Value float NULL,
    DetailLabel nvarchar(400) NULL
);
';
IF NOT EXISTS(SELECT 1 FROM sys.extended_properties WHERE class=6 AND major_id=TYPE_ID(N'viz.CategoryValue_v1') AND minor_id=0 AND name=N'TSQLViz.Owner') EXEC sys.sp_addextendedproperty @name=N'TSQLViz.Owner',@value=N'core-v1',@level0type=N'SCHEMA',@level0name=N'viz',@level1type=N'TYPE',@level1name=N'CategoryValue_v1';
-- src/core/types/XY_v1.sql
IF TYPE_ID(N'viz.XY_v1') IS NULL EXEC sys.sp_executesql N'CREATE TYPE viz.[XY_v1] AS TABLE (
    ItemKey nvarchar(200) COLLATE Latin1_General_100_BIN2 NOT NULL PRIMARY KEY,
    SeriesKey nvarchar(200) COLLATE Latin1_General_100_BIN2 NOT NULL,
    SeriesLabel nvarchar(400) NOT NULL,
    SeriesOrder int NOT NULL,
    PointOrder bigint NOT NULL,
    X float NOT NULL,
    Y float NULL,
    SizeValue float NULL,
    DetailLabel nvarchar(400) NULL
);
';
IF NOT EXISTS(SELECT 1 FROM sys.extended_properties WHERE class=6 AND major_id=TYPE_ID(N'viz.XY_v1') AND minor_id=0 AND name=N'TSQLViz.Owner') EXEC sys.sp_addextendedproperty @name=N'TSQLViz.Owner',@value=N'core-v1',@level0type=N'SCHEMA',@level0name=N'viz',@level1type=N'TYPE',@level1name=N'XY_v1';
-- src/core/types/Vertex_v1.sql
IF TYPE_ID(N'viz.Vertex_v1') IS NULL EXEC sys.sp_executesql N'CREATE TYPE viz.[Vertex_v1] AS TABLE (
    PathId int NOT NULL,
    VertexOrder int NOT NULL,
    X float NOT NULL,
    Y float NOT NULL,
    PRIMARY KEY(PathId,VertexOrder)
);
';
IF NOT EXISTS(SELECT 1 FROM sys.extended_properties WHERE class=6 AND major_id=TYPE_ID(N'viz.Vertex_v1') AND minor_id=0 AND name=N'TSQLViz.Owner') EXEC sys.sp_addextendedproperty @name=N'TSQLViz.Owner',@value=N'core-v1',@level0type=N'SCHEMA',@level0name=N'viz',@level1type=N'TYPE',@level1name=N'Vertex_v1';
-- src/core/types/Scene_v1.sql
IF TYPE_ID(N'viz.Scene_v1') IS NULL EXEC sys.sp_executesql N'CREATE TYPE viz.[Scene_v1] AS TABLE (
    Layer int NOT NULL,
    ElementOrder bigint NOT NULL,
    ElementKey nvarchar(200) COLLATE Latin1_General_100_BIN2 NOT NULL PRIMARY KEY,
    Kind varchar(24) NOT NULL,
    SeriesKey nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    ItemKey nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    Label nvarchar(400) NULL,
    Shape geometry NOT NULL
);
';
IF NOT EXISTS(SELECT 1 FROM sys.extended_properties WHERE class=6 AND major_id=TYPE_ID(N'viz.Scene_v1') AND minor_id=0 AND name=N'TSQLViz.Owner') EXEC sys.sp_addextendedproperty @name=N'TSQLViz.Owner',@value=N'core-v1',@level0type=N'SCHEMA',@level0name=N'viz',@level1type=N'TYPE',@level1name=N'Scene_v1';
-- src/core/metadata/LibraryVersion.sql
IF OBJECT_ID(N'viz.LibraryVersion',N'U') IS NULL EXEC sys.sp_executesql N'CREATE TABLE viz.LibraryVersion (
    Singleton bit NOT NULL PRIMARY KEY CHECK (Singleton=1),
    Version varchar(32) NOT NULL,
    InstalledUtc datetime2(3) NOT NULL
);
';
IF NOT EXISTS(SELECT 1 FROM sys.extended_properties WHERE class=1 AND major_id=OBJECT_ID(N'viz.LibraryVersion') AND minor_id=0 AND name=N'TSQLViz.Owner') EXEC sys.sp_addextendedproperty @name=N'TSQLViz.Owner',@value=N'core-v1',@level0type=N'SCHEMA',@level0name=N'viz',@level1type=N'TABLE',@level1name=N'LibraryVersion';
-- src/core/metadata/ObjectManifest.sql
IF OBJECT_ID(N'viz.ObjectManifest',N'U') IS NULL EXEC sys.sp_executesql N'CREATE TABLE viz.ObjectManifest (
    ObjectName sysname COLLATE Latin1_General_100_BIN2 NOT NULL PRIMARY KEY,
    ObjectKind varchar(12) NOT NULL,
    SourceHash varchar(64) NOT NULL,
    CatalogHash varbinary(32) NULL
);
';
IF NOT EXISTS(SELECT 1 FROM sys.extended_properties WHERE class=1 AND major_id=OBJECT_ID(N'viz.ObjectManifest') AND minor_id=0 AND name=N'TSQLViz.Owner') EXEC sys.sp_addextendedproperty @name=N'TSQLViz.Owner',@value=N'core-v1',@level0type=N'SCHEMA',@level0name=N'viz',@level1type=N'TABLE',@level1name=N'ObjectManifest';
-- src/core/text/GlyphStroke.sql
IF OBJECT_ID(N'viz.GlyphStroke',N'U') IS NULL EXEC sys.sp_executesql N'CREATE TABLE viz.GlyphStroke (
    CodePoint int NOT NULL CHECK(CodePoint BETWEEN 0 AND 1114111),
    StrokeOrder int NOT NULL, VertexOrder int NOT NULL,
    X decimal(8,4) NOT NULL CHECK(X BETWEEN 0 AND 0.6),
    Y decimal(8,4) NOT NULL CHECK(Y BETWEEN 0 AND 1),
    PRIMARY KEY(CodePoint,StrokeOrder,VertexOrder)
);
';
IF NOT EXISTS(SELECT 1 FROM sys.extended_properties WHERE class=1 AND major_id=OBJECT_ID(N'viz.GlyphStroke') AND minor_id=0 AND name=N'TSQLViz.Owner') EXEC sys.sp_addextendedproperty @name=N'TSQLViz.Owner',@value=N'core-v1',@level0type=N'SCHEMA',@level0name=N'viz',@level1type=N'TABLE',@level1name=N'GlyphStroke';
-- src/core/scales/Numbers.sql
EXEC sys.sp_executesql N'CREATE OR ALTER FUNCTION viz.Numbers(@Count int)
RETURNS TABLE WITH SCHEMABINDING AS RETURN
WITH d(n) AS (SELECT n FROM (VALUES(0),(1),(2),(3),(4),(5),(6),(7),(8),(9)) v(n))
SELECT a.n+10*b.n+100*c.n+1000*d.n+10000*e.n AS N
FROM d a CROSS JOIN d b CROSS JOIN d c CROSS JOIN d d CROSS JOIN d e
WHERE a.n+10*b.n+100*c.n+1000*d.n+10000*e.n < @Count AND @Count BETWEEN 0 AND 100000;
';
IF NOT EXISTS(SELECT 1 FROM sys.extended_properties WHERE class=1 AND major_id=OBJECT_ID(N'viz.Numbers') AND minor_id=0 AND name=N'TSQLViz.Owner') EXEC sys.sp_addextendedproperty @name=N'TSQLViz.Owner',@value=N'core-v1',@level0type=N'SCHEMA',@level0name=N'viz',@level1type=N'FUNCTION',@level1name=N'Numbers';
-- src/core/geometry/Point.sql
EXEC sys.sp_executesql N'CREATE OR ALTER FUNCTION viz.Point(@X float,@Y float) RETURNS geometry AS
BEGIN
    IF @X IS NULL OR @Y IS NULL OR ABS(@X)>1000000 OR ABS(@Y)>1000000 RETURN NULL;
    RETURN geometry::Point(@X,@Y,0);
END;
';
IF NOT EXISTS(SELECT 1 FROM sys.extended_properties WHERE class=1 AND major_id=OBJECT_ID(N'viz.Point') AND minor_id=0 AND name=N'TSQLViz.Owner') EXEC sys.sp_addextendedproperty @name=N'TSQLViz.Owner',@value=N'core-v1',@level0type=N'SCHEMA',@level0name=N'viz',@level1type=N'FUNCTION',@level1name=N'Point';
-- src/core/geometry/CoordinateText.sql
EXEC sys.sp_executesql N'CREATE OR ALTER FUNCTION viz.CoordinateText(@X float,@Y float) RETURNS varchar(100) AS
BEGIN
    RETURN CONVERT(varchar(48),@X,3)+'' ''+CONVERT(varchar(48),@Y,3);
END;
';
IF NOT EXISTS(SELECT 1 FROM sys.extended_properties WHERE class=1 AND major_id=OBJECT_ID(N'viz.CoordinateText') AND minor_id=0 AND name=N'TSQLViz.Owner') EXEC sys.sp_addextendedproperty @name=N'TSQLViz.Owner',@value=N'core-v1',@level0type=N'SCHEMA',@level0name=N'viz',@level1type=N'FUNCTION',@level1name=N'CoordinateText';
-- src/core/geometry/Segment.sql
EXEC sys.sp_executesql N'CREATE OR ALTER FUNCTION viz.Segment(@X1 float,@Y1 float,@X2 float,@Y2 float) RETURNS geometry AS
BEGIN
    IF viz.Point(@X1,@Y1) IS NULL OR viz.Point(@X2,@Y2) IS NULL OR (@X1=@X2 AND @Y1=@Y2) RETURN NULL;
    RETURN geometry::STGeomFromText(''LINESTRING(''+viz.CoordinateText(@X1,@Y1)+'',''+viz.CoordinateText(@X2,@Y2)+'')'',0);
END;
';
IF NOT EXISTS(SELECT 1 FROM sys.extended_properties WHERE class=1 AND major_id=OBJECT_ID(N'viz.Segment') AND minor_id=0 AND name=N'TSQLViz.Owner') EXEC sys.sp_addextendedproperty @name=N'TSQLViz.Owner',@value=N'core-v1',@level0type=N'SCHEMA',@level0name=N'viz',@level1type=N'FUNCTION',@level1name=N'Segment';
-- src/core/geometry/Rect.sql
EXEC sys.sp_executesql N'CREATE OR ALTER FUNCTION viz.Rect(@X float,@Y float,@Width float,@Height float) RETURNS geometry AS
BEGIN
    IF @Width IS NULL OR @Height IS NULL OR @Width<=0 OR @Height<=0 OR @Width>2000000 OR @Height>2000000 RETURN NULL;
    IF viz.Point(@X,@Y) IS NULL OR viz.Point(@X+@Width,@Y+@Height) IS NULL RETURN NULL;
    IF @X+@Width=@X OR @Y+@Height=@Y RETURN NULL;
    RETURN geometry::STGeomFromText(''POLYGON((''+viz.CoordinateText(@X,@Y)+'',''+viz.CoordinateText(@X+@Width,@Y)+'',''+
      viz.CoordinateText(@X+@Width,@Y+@Height)+'',''+viz.CoordinateText(@X,@Y+@Height)+'',''+viz.CoordinateText(@X,@Y)+''))'',0);
END;
';
IF NOT EXISTS(SELECT 1 FROM sys.extended_properties WHERE class=1 AND major_id=OBJECT_ID(N'viz.Rect') AND minor_id=0 AND name=N'TSQLViz.Owner') EXEC sys.sp_addextendedproperty @name=N'TSQLViz.Owner',@value=N'core-v1',@level0type=N'SCHEMA',@level0name=N'viz',@level1type=N'FUNCTION',@level1name=N'Rect';
-- src/core/geometry/Circle.sql
EXEC sys.sp_executesql N'CREATE OR ALTER FUNCTION viz.Circle(@CX float,@CY float,@Radius float) RETURNS geometry AS
BEGIN
    IF @CX IS NULL OR @CY IS NULL OR @Radius IS NULL OR @Radius<=0 OR @Radius>1000000 RETURN NULL;
    IF ABS(@CX)+@Radius>1000000 OR ABS(@CY)+@Radius>1000000 RETURN NULL;
    IF @CX+@Radius=@CX OR @CY+@Radius=@CY RETURN NULL;
    DECLARE @Wkt varchar(max), @Shape geometry;
    SELECT @Wkt=STRING_AGG(CONVERT(varchar(max),viz.CoordinateText(
      CASE WHEN N=64 THEN @CX+@Radius ELSE @CX+@Radius*COS(2*PI()*N/64) END,
      CASE WHEN N=64 THEN @CY ELSE @CY+@Radius*SIN(2*PI()*N/64) END)),'','') WITHIN GROUP(ORDER BY N)
    FROM viz.Numbers(65);
    SET @Shape=geometry::STGeomFromText(''POLYGON((''+@Wkt+''))'',0);
    IF @Shape.STIsValid()=0 RETURN NULL;
    RETURN @Shape;
END;
';
IF NOT EXISTS(SELECT 1 FROM sys.extended_properties WHERE class=1 AND major_id=OBJECT_ID(N'viz.Circle') AND minor_id=0 AND name=N'TSQLViz.Owner') EXEC sys.sp_addextendedproperty @name=N'TSQLViz.Owner',@value=N'core-v1',@level0type=N'SCHEMA',@level0name=N'viz',@level1type=N'FUNCTION',@level1name=N'Circle';
-- src/core/geometry/Polyline.sql
EXEC sys.sp_executesql N'CREATE OR ALTER FUNCTION viz.Polyline(@Vertices viz.Vertex_v1 READONLY) RETURNS geometry AS
BEGIN
    IF (SELECT COUNT(DISTINCT PathId) FROM @Vertices)<>1 RETURN NULL;
    IF (SELECT COUNT_BIG(*) FROM @Vertices)>100000 RETURN NULL;
    IF EXISTS(SELECT 1 FROM @Vertices WHERE ABS(X)>1000000 OR ABS(Y)>1000000) RETURN NULL;
    DECLARE @Clean TABLE(N int PRIMARY KEY,X float,Y float);
    INSERT @Clean SELECT VertexOrder,X,Y FROM (
      SELECT *,LAG(X) OVER(ORDER BY VertexOrder) PX,LAG(Y) OVER(ORDER BY VertexOrder) PY FROM @Vertices
    ) v WHERE PX IS NULL OR X<>PX OR Y<>PY;
    IF (SELECT COUNT(*) FROM (SELECT DISTINCT X,Y FROM @Clean) d)<2 RETURN NULL;
    DECLARE @Wkt varchar(max),@First varchar(100),@Last varchar(100);
    SELECT @Wkt=STRING_AGG(CONVERT(varchar(max),viz.CoordinateText(X,Y)),'','') WITHIN GROUP(ORDER BY N) FROM @Clean;
    SELECT TOP(1) @First=viz.CoordinateText(X,Y) FROM @Clean ORDER BY N;
    SELECT TOP(1) @Last=viz.CoordinateText(X,Y) FROM @Clean ORDER BY N DESC;
    
    RETURN geometry::STGeomFromText(''LINESTRING(''+@Wkt+'')'',0);
END;
';
IF NOT EXISTS(SELECT 1 FROM sys.extended_properties WHERE class=1 AND major_id=OBJECT_ID(N'viz.Polyline') AND minor_id=0 AND name=N'TSQLViz.Owner') EXEC sys.sp_addextendedproperty @name=N'TSQLViz.Owner',@value=N'core-v1',@level0type=N'SCHEMA',@level0name=N'viz',@level1type=N'FUNCTION',@level1name=N'Polyline';
-- src/core/geometry/Polygon.sql
EXEC sys.sp_executesql N'CREATE OR ALTER FUNCTION viz.Polygon(@Vertices viz.Vertex_v1 READONLY) RETURNS geometry AS
BEGIN
    IF (SELECT COUNT(DISTINCT PathId) FROM @Vertices)<>1 RETURN NULL;
    IF (SELECT COUNT_BIG(*) FROM @Vertices)>100000 RETURN NULL;
    IF EXISTS(SELECT 1 FROM @Vertices WHERE ABS(X)>1000000 OR ABS(Y)>1000000) RETURN NULL;
    DECLARE @Clean TABLE(N int PRIMARY KEY,X float,Y float);
    INSERT @Clean SELECT VertexOrder,X,Y FROM (
      SELECT *,LAG(X) OVER(ORDER BY VertexOrder) PX,LAG(Y) OVER(ORDER BY VertexOrder) PY FROM @Vertices
    ) v WHERE PX IS NULL OR X<>PX OR Y<>PY;
    IF (SELECT COUNT(*) FROM (SELECT DISTINCT X,Y FROM @Clean) d)<3 RETURN NULL;
    DECLARE @Wkt varchar(max),@First varchar(100),@Last varchar(100);
    SELECT @Wkt=STRING_AGG(CONVERT(varchar(max),viz.CoordinateText(X,Y)),'','') WITHIN GROUP(ORDER BY N) FROM @Clean;
    SELECT TOP(1) @First=viz.CoordinateText(X,Y) FROM @Clean ORDER BY N;
    SELECT TOP(1) @Last=viz.CoordinateText(X,Y) FROM @Clean ORDER BY N DESC;
    IF @First<>@Last SET @Wkt=@Wkt+'',''+@First;
    RETURN geometry::STGeomFromText(''POLYGON((''+@Wkt+''))'',0);
END;
';
IF NOT EXISTS(SELECT 1 FROM sys.extended_properties WHERE class=1 AND major_id=OBJECT_ID(N'viz.Polygon') AND minor_id=0 AND name=N'TSQLViz.Owner') EXEC sys.sp_addextendedproperty @name=N'TSQLViz.Owner',@value=N'core-v1',@level0type=N'SCHEMA',@level0name=N'viz',@level1type=N'FUNCTION',@level1name=N'Polygon';
-- src/core/scales/ScaleLinear.sql
EXEC sys.sp_executesql N'CREATE OR ALTER FUNCTION viz.ScaleLinear(@Value float,@DomainMin float,@DomainMax float,@RangeMin float,@RangeMax float,@Clamp bit)
RETURNS float AS BEGIN
    IF @Value IS NULL OR @DomainMin IS NULL OR @DomainMax IS NULL OR @RangeMin IS NULL OR @RangeMax IS NULL OR @Clamp IS NULL RETURN NULL;
    IF ABS(@Value)>1e16 OR ABS(@DomainMin)>1e16 OR ABS(@DomainMax)>1e16 OR ABS(@RangeMin)>1000000 OR ABS(@RangeMax)>1000000 OR @DomainMin>=@DomainMax RETURN NULL;
    IF @Clamp=1 AND @Value<=@DomainMin RETURN @RangeMin;
    IF @Clamp=1 AND @Value>=@DomainMax RETURN @RangeMax;
    IF @RangeMin=@RangeMax RETURN @RangeMin;
    -- Reject numerically unrepresentable extrapolation before division.
    IF ABS(@DomainMax-@DomainMin)<1 AND ABS(@Value-@DomainMin)>1e300*ABS(@DomainMax-@DomainMin) RETURN NULL;
    DECLARE @T float=(@Value-@DomainMin)/(@DomainMax-@DomainMin);
    DECLARE @Result float=@RangeMin+@T*(@RangeMax-@RangeMin);
    IF ABS(@Result)>1000000 RETURN NULL;
    RETURN @Result;
END;
';
IF NOT EXISTS(SELECT 1 FROM sys.extended_properties WHERE class=1 AND major_id=OBJECT_ID(N'viz.ScaleLinear') AND minor_id=0 AND name=N'TSQLViz.Owner') EXEC sys.sp_addextendedproperty @name=N'TSQLViz.Owner',@value=N'core-v1',@level0type=N'SCHEMA',@level0name=N'viz',@level1type=N'FUNCTION',@level1name=N'ScaleLinear';
-- src/core/scales/ScaleLog.sql
EXEC sys.sp_executesql N'CREATE OR ALTER FUNCTION viz.ScaleLog(@Value float,@DomainMin float,@DomainMax float,@RangeMin float,@RangeMax float,@Base float)
RETURNS float AS BEGIN
    IF @Value IS NULL OR @DomainMin IS NULL OR @DomainMax IS NULL OR @Base IS NULL OR @Base<=1 OR @Base>1e16 RETURN NULL;
    IF @Value<=0 OR @DomainMin<=0 OR @DomainMin>=@DomainMax OR @Value>1e16 OR @DomainMax>1e16 RETURN NULL;
    RETURN viz.ScaleLinear(LOG(@Value),LOG(@DomainMin),LOG(@DomainMax),@RangeMin,@RangeMax,0);
END;
';
IF NOT EXISTS(SELECT 1 FROM sys.extended_properties WHERE class=1 AND major_id=OBJECT_ID(N'viz.ScaleLog') AND minor_id=0 AND name=N'TSQLViz.Owner') EXEC sys.sp_addextendedproperty @name=N'TSQLViz.Owner',@value=N'core-v1',@level0type=N'SCHEMA',@level0name=N'viz',@level1type=N'FUNCTION',@level1name=N'ScaleLog';
-- src/core/scales/ScaleBand.sql
EXEC sys.sp_executesql N'CREATE OR ALTER FUNCTION viz.ScaleBand(@Index int,@Count int,@RangeMin float,@RangeMax float,@PaddingInner float,@PaddingOuter float)
RETURNS TABLE AS RETURN
SELECT BandStart=@RangeMin+s.Step*(@PaddingOuter+@Index),BandWidth=s.Step*(1-@PaddingInner),
       BandCenter=@RangeMin+s.Step*(@PaddingOuter+@Index+(1-@PaddingInner)/2)
FROM (VALUES(CASE WHEN ABS(@RangeMin)<=1000000 AND ABS(@RangeMax)<=1000000 AND @PaddingInner>=0 AND @PaddingInner<1 AND @PaddingOuter BETWEEN 0 AND 10000 AND @Count BETWEEN 1 AND 10000
 THEN (@RangeMax-@RangeMin)/NULLIF(CASE WHEN @Count-@PaddingInner+2*@PaddingOuter<1 THEN 1 ELSE @Count-@PaddingInner+2*@PaddingOuter END,0) END)) s(Step)
WHERE @Index>=0 AND @Index<@Count AND @Count BETWEEN 1 AND 10000 AND @RangeMin<@RangeMax
  AND ABS(@RangeMin)<=1000000 AND ABS(@RangeMax)<=1000000 AND @PaddingInner>=0 AND @PaddingInner<1 AND @PaddingOuter BETWEEN 0 AND 10000;
';
IF NOT EXISTS(SELECT 1 FROM sys.extended_properties WHERE class=1 AND major_id=OBJECT_ID(N'viz.ScaleBand') AND minor_id=0 AND name=N'TSQLViz.Owner') EXEC sys.sp_addextendedproperty @name=N'TSQLViz.Owner',@value=N'core-v1',@level0type=N'SCHEMA',@level0name=N'viz',@level1type=N'FUNCTION',@level1name=N'ScaleBand';
-- src/core/scales/BubbleRadius.sql
EXEC sys.sp_executesql N'CREATE OR ALTER FUNCTION viz.BubbleRadius(@Value float,@MaxSizeValue float,@MaxRadius float) RETURNS float AS
BEGIN
    IF @Value IS NULL OR @MaxSizeValue IS NULL OR @MaxRadius IS NULL OR @Value<=0 OR @Value>@MaxSizeValue OR @MaxSizeValue>1e15 OR @MaxRadius<=0 OR @MaxRadius>1000000 RETURN NULL;
    RETURN @MaxRadius*SQRT(@Value/@MaxSizeValue);
END;
';
IF NOT EXISTS(SELECT 1 FROM sys.extended_properties WHERE class=1 AND major_id=OBJECT_ID(N'viz.BubbleRadius') AND minor_id=0 AND name=N'TSQLViz.Owner') EXEC sys.sp_addextendedproperty @name=N'TSQLViz.Owner',@value=N'core-v1',@level0type=N'SCHEMA',@level0name=N'viz',@level1type=N'FUNCTION',@level1name=N'BubbleRadius';
-- src/core/scales/TimeToEpoch.sql
EXEC sys.sp_executesql N'CREATE OR ALTER FUNCTION viz.TimeToEpoch(@Utc datetime2(3)) RETURNS float AS
BEGIN
    IF @Utc IS NULL OR @Utc<''19000101'' OR @Utc>=''21010101'' RETURN NULL;
    RETURN CONVERT(float,DATEDIFF_BIG(millisecond,CONVERT(datetime2(3),''20000101''),@Utc));
END;
';
IF NOT EXISTS(SELECT 1 FROM sys.extended_properties WHERE class=1 AND major_id=OBJECT_ID(N'viz.TimeToEpoch') AND minor_id=0 AND name=N'TSQLViz.Owner') EXEC sys.sp_addextendedproperty @name=N'TSQLViz.Owner',@value=N'core-v1',@level0type=N'SCHEMA',@level0name=N'viz',@level1type=N'FUNCTION',@level1name=N'TimeToEpoch';
-- src/core/scales/EpochToTime.sql
EXEC sys.sp_executesql N'CREATE OR ALTER FUNCTION viz.EpochToTime(@Milliseconds float) RETURNS datetime2(3) AS
BEGIN
    IF @Milliseconds IS NULL OR @Milliseconds<-3155673600000 OR @Milliseconds>=3187296000000 OR FLOOR(@Milliseconds)<>@Milliseconds RETURN NULL;
    DECLARE @Days int=CONVERT(int,FLOOR(@Milliseconds/86400000.0));
    DECLARE @Rest int=CONVERT(int,@Milliseconds-CONVERT(bigint,@Days)*86400000);
    RETURN DATEADD(millisecond,@Rest,DATEADD(day,@Days,CONVERT(datetime2(3),''20000101'')));
END;
';
IF NOT EXISTS(SELECT 1 FROM sys.extended_properties WHERE class=1 AND major_id=OBJECT_ID(N'viz.EpochToTime') AND minor_id=0 AND name=N'TSQLViz.Owner') EXEC sys.sp_addextendedproperty @name=N'TSQLViz.Owner',@value=N'core-v1',@level0type=N'SCHEMA',@level0name=N'viz',@level1type=N'FUNCTION',@level1name=N'EpochToTime';
-- src/core/scales/TickStep.sql
EXEC sys.sp_executesql N'CREATE OR ALTER FUNCTION viz.TickStep(@DomainMin float,@DomainMax float,@TargetCount int) RETURNS float AS
BEGIN
    IF @DomainMin IS NULL OR @DomainMax IS NULL OR @DomainMin>=@DomainMax OR ABS(@DomainMin)>1e16 OR ABS(@DomainMax)>1e16 OR @TargetCount IS NULL OR @TargetCount NOT BETWEEN 2 AND 12 RETURN NULL;
    DECLARE @Raw float=(@DomainMax-@DomainMin)/(@TargetCount-1);
    -- Below 1e-300, decimal tick generation cannot maintain its precision contract.
    IF @Raw<1e-300 RETURN NULL;
    DECLARE @Power float=POWER(CONVERT(float,10),FLOOR(LOG10(@Raw)));
    DECLARE @Unit float=@Raw/@Power;
    RETURN @Power*CASE WHEN @Unit<=1 THEN 1 WHEN @Unit<=2 THEN 2 WHEN @Unit<=2.5 THEN 2.5 WHEN @Unit<=5 THEN 5 ELSE 10 END;
END;
';
IF NOT EXISTS(SELECT 1 FROM sys.extended_properties WHERE class=1 AND major_id=OBJECT_ID(N'viz.TickStep') AND minor_id=0 AND name=N'TSQLViz.Owner') EXEC sys.sp_addextendedproperty @name=N'TSQLViz.Owner',@value=N'core-v1',@level0type=N'SCHEMA',@level0name=N'viz',@level1type=N'FUNCTION',@level1name=N'TickStep';
-- src/core/scales/TicksLinear.sql
EXEC sys.sp_executesql N'CREATE OR ALTER FUNCTION viz.TicksLinear(@DomainMin float,@DomainMax float,@TargetCount int)
RETURNS TABLE AS RETURN
WITH s AS (SELECT viz.TickStep(@DomainMin,@DomainMax,@TargetCount) Step),
v AS (SELECT (CEILING(@DomainMin/NULLIF(Step,0))+N)*Step Value FROM s CROSS JOIN viz.Numbers(13) WHERE Step IS NOT NULL),
t AS (SELECT DISTINCT Value FROM v WHERE Value BETWEEN @DomainMin AND @DomainMax),
r AS (SELECT Value FROM t WHERE (SELECT COUNT(*) FROM t)>=2
      UNION ALL SELECT @DomainMin WHERE (SELECT COUNT(*) FROM t)<2 AND (SELECT Step FROM s) IS NOT NULL
      UNION ALL SELECT @DomainMax WHERE (SELECT COUNT(*) FROM t)<2 AND (SELECT Step FROM s) IS NOT NULL)
SELECT CONVERT(int,ROW_NUMBER() OVER(ORDER BY Value)-1) TickOrder,Value FROM r;
';
IF NOT EXISTS(SELECT 1 FROM sys.extended_properties WHERE class=1 AND major_id=OBJECT_ID(N'viz.TicksLinear') AND minor_id=0 AND name=N'TSQLViz.Owner') EXEC sys.sp_addextendedproperty @name=N'TSQLViz.Owner',@value=N'core-v1',@level0type=N'SCHEMA',@level0name=N'viz',@level1type=N'FUNCTION',@level1name=N'TicksLinear';
-- src/core/scales/NiceDomain.sql
EXEC sys.sp_executesql N'CREATE OR ALTER FUNCTION viz.NiceDomain(@DomainMin float,@DomainMax float,@TargetCount int)
RETURNS TABLE AS RETURN
SELECT DomainMin=FLOOR(@DomainMin/NULLIF(Step,0))*Step,DomainMax=CEILING(@DomainMax/NULLIF(Step,0))*Step,Step
FROM (VALUES(viz.TickStep(@DomainMin,@DomainMax,@TargetCount))) s(Step)
WHERE Step IS NOT NULL AND ABS(FLOOR(@DomainMin/NULLIF(Step,0))*Step)<=1e16 AND ABS(CEILING(@DomainMax/NULLIF(Step,0))*Step)<=1e16;
';
IF NOT EXISTS(SELECT 1 FROM sys.extended_properties WHERE class=1 AND major_id=OBJECT_ID(N'viz.NiceDomain') AND minor_id=0 AND name=N'TSQLViz.Owner') EXEC sys.sp_addextendedproperty @name=N'TSQLViz.Owner',@value=N'core-v1',@level0type=N'SCHEMA',@level0name=N'viz',@level1type=N'FUNCTION',@level1name=N'NiceDomain';
-- src/core/scales/TicksLog.sql
EXEC sys.sp_executesql N'CREATE OR ALTER FUNCTION viz.TicksLog(@DomainMin float,@DomainMax float)
RETURNS TABLE AS RETURN
WITH bounds AS (SELECT CEILING(LOG10(NULLIF(CASE WHEN @DomainMin>0 THEN @DomainMin END,0))) Lo,
 FLOOR(LOG10(NULLIF(CASE WHEN @DomainMax>0 THEN @DomainMax END,0))) Hi
 WHERE @DomainMin>0 AND @DomainMin<@DomainMax AND @DomainMax<=1e16 AND @DomainMin>=1e-300),
p AS (SELECT DISTINCT CONVERT(int,Lo+FLOOR(N*(Hi-Lo)/CASE WHEN Hi-Lo<11 THEN NULLIF(Hi-Lo,0) ELSE 11 END)) E
 FROM bounds CROSS JOIN viz.Numbers(12) WHERE Hi>=Lo AND N<=Hi-Lo),
t AS (SELECT POWER(CONVERT(float,10),E) Value FROM p WHERE E IS NOT NULL),
r AS (SELECT Value FROM t WHERE (SELECT COUNT(*) FROM t)>=2
 UNION ALL SELECT @DomainMin FROM bounds WHERE (SELECT COUNT(*) FROM t)<2
 UNION ALL SELECT @DomainMax FROM bounds WHERE (SELECT COUNT(*) FROM t)<2)
SELECT CONVERT(int,ROW_NUMBER() OVER(ORDER BY Value)-1) TickOrder,Value FROM r;
';
IF NOT EXISTS(SELECT 1 FROM sys.extended_properties WHERE class=1 AND major_id=OBJECT_ID(N'viz.TicksLog') AND minor_id=0 AND name=N'TSQLViz.Owner') EXEC sys.sp_addextendedproperty @name=N'TSQLViz.Owner',@value=N'core-v1',@level0type=N'SCHEMA',@level0name=N'viz',@level1type=N'FUNCTION',@level1name=N'TicksLog';
-- src/core/scales/TicksTime.sql
EXEC sys.sp_executesql N'CREATE OR ALTER FUNCTION viz.TicksTime(@DomainMin float,@DomainMax float,@TargetCount int)
RETURNS TABLE AS RETURN
WITH b AS (SELECT (CASE WHEN @DomainMin>=-3155673600000 AND @DomainMax<3187296000000 THEN @DomainMax-@DomainMin END)/NULLIF(CONVERT(bigint,@TargetCount)-1,0) Raw
 WHERE viz.EpochToTime(@DomainMin) IS NOT NULL AND viz.EpochToTime(@DomainMax) IS NOT NULL AND @DomainMin<@DomainMax AND @TargetCount BETWEEN 2 AND 12),
s AS (SELECT COALESCE((SELECT MIN(CONVERT(float,Ms)) FROM (VALUES(1000),(5000),(15000),(30000),(60000),(300000),(900000),(1800000),(3600000),(10800000),(21600000),(43200000),(86400000),(604800000)) c(Ms) WHERE Ms>=Raw),CEILING(Raw/604800000)*604800000) Step FROM b),
a AS (SELECT Step,CASE WHEN Step>=604800000 THEN CONVERT(float,172800000) ELSE 0 END Anchor FROM s),
t AS (SELECT (CEILING((@DomainMin-Anchor)/Step)+N)*Step+Anchor Value FROM a CROSS JOIN viz.Numbers(13)),
v AS (SELECT Value FROM t WHERE Value BETWEEN @DomainMin AND @DomainMax),
r AS (SELECT Value FROM v WHERE (SELECT COUNT(*) FROM v)>=2
 UNION ALL SELECT @DomainMin FROM b WHERE (SELECT COUNT(*) FROM v)<2
 UNION ALL SELECT @DomainMax FROM b WHERE (SELECT COUNT(*) FROM v)<2)
SELECT CONVERT(int,ROW_NUMBER() OVER(ORDER BY Value)-1) TickOrder,Value FROM r;
';
IF NOT EXISTS(SELECT 1 FROM sys.extended_properties WHERE class=1 AND major_id=OBJECT_ID(N'viz.TicksTime') AND minor_id=0 AND name=N'TSQLViz.Owner') EXEC sys.sp_addextendedproperty @name=N'TSQLViz.Owner',@value=N'core-v1',@level0type=N'SCHEMA',@level0name=N'viz',@level1type=N'FUNCTION',@level1name=N'TicksTime';
-- src/core/render/RenderScene.sql
EXEC sys.sp_executesql N'CREATE OR ALTER PROCEDURE viz.RenderScene @Scene viz.Scene_v1 READONLY AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS(SELECT 1 FROM @Scene WHERE Kind COLLATE Latin1_General_100_BIN2 NOT IN (''frame'',''grid'',''axis'',''mark'',''text'',''legend'',''notice''))
        THROW 51001,''Scene Kind is not part of Scene_v1.'',1;
    IF EXISTS(SELECT 1 FROM @Scene WHERE Shape.STIsValid()=0 OR Shape.STSrid<>0 OR Shape.HasZ=1 OR Shape.HasM=1)
        THROW 51003,''Scene requires valid two-dimensional geometry with SRID 0.'',1;
    IF EXISTS(SELECT 1 FROM @Scene WHERE Shape.STIsEmpty()=1)
        THROW 51003,''Empty shapes are not renderable.'',1;
    IF (SELECT COUNT_BIG(*) FROM @Scene)>2000 THROW 51004,''Scene row budget exceeded (2000).'',1;
    IF EXISTS(SELECT 1 FROM @Scene WHERE DATALENGTH(Shape.Serialize())>32000)
        THROW 51004,''Single shape byte budget exceeded (32000).'',1;
    IF (SELECT SUM(CONVERT(bigint,Shape.STNumPoints())) FROM @Scene)>100000
        THROW 51004,''Scene point budget exceeded (100000).'',1;
    IF (SELECT SUM(CONVERT(bigint,DATALENGTH(Shape.Serialize()))) FROM @Scene)>16777216
        THROW 51004,''Scene total byte budget exceeded (16 MiB).'',1;
    IF EXISTS(SELECT 1 FROM @Scene CROSS APPLY(SELECT Shape.STEnvelope() E) e
      CROSS APPLY viz.Numbers(5) n WHERE N<e.E.STNumPoints()
      AND (ABS(e.E.STPointN(N+1).STX)>1000000 OR ABS(e.E.STPointN(N+1).STY)>1000000))
        THROW 51004,''Scene coordinate budget exceeded (1000000).'',1;
    SELECT Layer,ElementOrder,ElementKey,Kind,SeriesKey,ItemKey,Label,Shape
    FROM @Scene ORDER BY Layer,ElementOrder,ElementKey;
END;
';
IF NOT EXISTS(SELECT 1 FROM sys.extended_properties WHERE class=1 AND major_id=OBJECT_ID(N'viz.RenderScene') AND minor_id=0 AND name=N'TSQLViz.Owner') EXEC sys.sp_addextendedproperty @name=N'TSQLViz.Owner',@value=N'core-v1',@level0type=N'SCHEMA',@level0name=N'viz',@level1type=N'PROCEDURE',@level1name=N'RenderScene';
IF DATABASE_PRINCIPAL_ID('viz_user') IS NULL CREATE ROLE viz_user AUTHORIZATION dbo;
GRANT EXECUTE, REFERENCES ON TYPE::viz.[CategoryValue_v1] TO viz_user;
GRANT EXECUTE, REFERENCES ON TYPE::viz.[XY_v1] TO viz_user;
GRANT EXECUTE, REFERENCES ON TYPE::viz.[Vertex_v1] TO viz_user;
GRANT EXECUTE, REFERENCES ON TYPE::viz.[Scene_v1] TO viz_user;
GRANT EXECUTE ON OBJECT::viz.[Point] TO viz_user;
GRANT EXECUTE ON OBJECT::viz.[Segment] TO viz_user;
GRANT EXECUTE ON OBJECT::viz.[Rect] TO viz_user;
GRANT EXECUTE ON OBJECT::viz.[Circle] TO viz_user;
GRANT EXECUTE ON OBJECT::viz.[Polyline] TO viz_user;
GRANT EXECUTE ON OBJECT::viz.[Polygon] TO viz_user;
GRANT EXECUTE ON OBJECT::viz.[ScaleLinear] TO viz_user;
GRANT EXECUTE ON OBJECT::viz.[ScaleLog] TO viz_user;
GRANT SELECT ON OBJECT::viz.[ScaleBand] TO viz_user;
GRANT EXECUTE ON OBJECT::viz.[BubbleRadius] TO viz_user;
GRANT EXECUTE ON OBJECT::viz.[TimeToEpoch] TO viz_user;
GRANT EXECUTE ON OBJECT::viz.[EpochToTime] TO viz_user;
GRANT SELECT ON OBJECT::viz.[TicksLinear] TO viz_user;
GRANT SELECT ON OBJECT::viz.[NiceDomain] TO viz_user;
GRANT SELECT ON OBJECT::viz.[TicksLog] TO viz_user;
GRANT SELECT ON OBJECT::viz.[TicksTime] TO viz_user;
GRANT EXECUTE ON OBJECT::viz.[RenderScene] TO viz_user;
    EXEC sys.sp_executesql N'DELETE FROM viz.ObjectManifest;';
    DECLARE @SourceHash varchar(64);
    DECLARE save_objects CURSOR LOCAL FAST_FORWARD FOR SELECT Name,Kind,SourceHash FROM @Expected;
    OPEN save_objects;
    FETCH NEXT FROM save_objects INTO @Name,@Kind,@SourceHash;
    WHILE @@FETCH_STATUS=0 BEGIN
        SET @CatalogHash=NULL;
        IF @Kind IN ('TABLE','TYPE') BEGIN
            SET @CatalogId=CASE WHEN @Kind='TYPE' THEN (SELECT type_table_object_id FROM sys.table_types WHERE schema_id=SCHEMA_ID('viz') AND name=@Name) ELSE OBJECT_ID(N'viz.'+QUOTENAME(@Name)) END;
            SET @Shape=(SELECT column_id,name,system_type_id,user_type_id,max_length,precision,scale,collation_name,is_nullable,is_identity FROM sys.columns WHERE object_id=@CatalogId ORDER BY column_id FOR XML RAW);
            SET @Shape=@Shape+(SELECT i.index_id,i.is_unique,i.is_primary_key,c.column_id,c.key_ordinal,c.is_descending_key FROM sys.indexes i JOIN sys.index_columns c ON c.object_id=i.object_id AND c.index_id=i.index_id WHERE i.object_id=@CatalogId ORDER BY i.index_id,c.index_column_id FOR XML RAW);
            SET @Shape=@Shape+COALESCE((SELECT definition FROM sys.check_constraints WHERE parent_object_id=@CatalogId ORDER BY definition FOR XML RAW),N'');
            SET @CatalogHash=HASHBYTES('SHA2_256',@Shape);
        END;
        EXEC sys.sp_executesql N'INSERT viz.ObjectManifest VALUES(@n,@k,@s,@h);',N'@n sysname,@k varchar(12),@s varchar(64),@h varbinary(32)',@Name,@Kind,@SourceHash,@CatalogHash;
        FETCH NEXT FROM save_objects INTO @Name,@Kind,@SourceHash;
    END;
    CLOSE save_objects; DEALLOCATE save_objects;
    EXEC sys.sp_executesql N'INSERT viz.ObjectManifest VALUES(N''@role:viz_user'',''ROLE'','''',NULL);';
EXEC sys.sp_executesql N'IF NOT EXISTS(SELECT 1 FROM viz.LibraryVersion) INSERT viz.LibraryVersion VALUES(1,''0.1.0-s2'',SYSUTCDATETIME());';
    COMMIT;
END TRY
BEGIN CATCH
    IF XACT_STATE()<>0 ROLLBACK;
    THROW;
END CATCH;
