SET NOCOUNT ON;
GO
CREATE PROCEDURE #Assert @Pass bit,@Case nvarchar(200) AS
BEGIN IF @Pass IS NULL OR @Pass=0 THROW 51998,@Case,1; PRINT N'PASS '+@Case; END;
GO
CREATE PROCEDURE #Error @Sql nvarchar(max),@Expected int,@Case nvarchar(200) AS
BEGIN
 DECLARE @Actual int=0,@Message nvarchar(2048);
 BEGIN TRY EXEC sys.sp_executesql @Sql; END TRY BEGIN CATCH SELECT @Actual=ERROR_NUMBER(),@Message=ERROR_MESSAGE(); END CATCH;
 IF @Actual<>@Expected BEGIN SET @Message=CONCAT(@Case,N': expected ',@Expected,N', got ',@Actual,N': ',@Message); THROW 51998,@Message,1; END;
 PRINT N'PASS '+@Case;
END;
GO
DECLARE @Ok bit,@G geometry,@S viz.Scene_v1,@Again viz.Scene_v1,@Bars viz.CategoryValue_v1,@XY viz.XY_v1;
IF EXISTS(SELECT 1 FROM(VALUES(0),(1),(9),(10),(11),(65),(999),(1000),(10001),(100000))v(C) CROSS APPLY(SELECT COUNT(*) N,MIN(N) Lo,MAX(N) Hi FROM viz.Numbers(v.C))n WHERE n.N<>v.C OR (v.C>0 AND (Lo<>0 OR Hi<>v.C-1))) THROW 51998,'Numbers digit-pruning regression.',1;
PRINT 'PASS Core Numbers retains exact counts across decimal boundaries';
SET @Ok=CASE WHEN (SELECT COUNT(DISTINCT CodePoint) FROM viz.GlyphStroke)=83 AND NOT EXISTS(SELECT CodePoint,StrokeOrder FROM viz.GlyphStroke GROUP BY CodePoint,StrokeOrder HAVING COUNT(*)<2 OR (MIN(X)=MAX(X) AND MIN(Y)=MAX(Y))) THEN 1 ELSE 0 END;
EXEC #Assert @Ok,N'T01 Original 83-glyph atlas has nondegenerate strokes';
DECLARE @Alphabet nvarchar(400)=N'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 .,:;!?%/\-+()[]_=<>#*';
IF EXISTS(SELECT 1 FROM viz.Numbers(LEN(@Alphabet))n CROSS APPLY(SELECT viz.Text(SUBSTRING(@Alphabet,n.N+1,1),0,0,18,0) G)g WHERE SUBSTRING(@Alphabet,n.N+1,1)<>N' ' AND (G IS NULL OR G.STIsValid()=0)) THROW 51998,'Invalid glyph.',1;
PRINT 'PASS T01 Every glyph produces valid geometry';
DECLARE @Sizes TABLE(Size float); INSERT @Sizes VALUES(6),(18),(24),(40);
IF EXISTS(SELECT 1 FROM @Sizes CROSS APPLY viz.MeasureText(N'MWgj 0?',Size)m CROSS APPLY(SELECT viz.Text(N'MWgj 0?',20,30,Size,0).STEnvelope() G)g CROSS APPLY viz.Numbers(5)n
 WHERE g.G.STPointN(n.N+1).STX<19.25-0.01 OR g.G.STPointN(n.N+1).STX>19.25+m.Width+0.01 OR g.G.STPointN(n.N+1).STY<29.25-0.01 OR g.G.STPointN(n.N+1).STY>29.25+m.Height+0.01) THROW 51998,'MeasureText underestimates envelope.',1;
PRINT 'PASS T02 Text envelopes at all four sizes';
IF EXISTS(SELECT 1 FROM @Sizes CROSS JOIN viz.Numbers(80)n CROSS APPLY viz.MeasureText(REPLICATE(N'W',n.N+3),Size)m WHERE viz.FitText(REPLICATE(N'W',n.N+3),Size,m.Width,100)<>REPLICATE(N'W',n.N+3)) THROW 51998,'FitText truncates an exactly fitting label.',1;
PRINT 'PASS T02 Exactly measured labels retain every character';
SET @G=viz.Text(N'ABC',20,30,24,PI()/2).STEnvelope();
SET @Ok=CASE WHEN ABS(@G.STPointN(3).STX-@G.STPointN(1).STX-25.5)<0.2 THEN 1 ELSE 0 END;
EXEC #Assert @Ok,N'T02 Rotation uses the supplied baseline origin';
SET @Ok=CASE WHEN viz.DisplayText(N'ÄÖÜäöüßµ–—−…😀漢') COLLATE Latin1_General_100_BIN2=N'AeOeUeaeoeuessu---...??' AND viz.Text(N'   ',0,0,18,0) IS NULL AND viz.Text(N'',0,0,18,0) IS NULL AND viz.Text(NULL,0,0,18,0) IS NULL THEN 1 ELSE 0 END;
EXEC #Assert @Ok,N'T03 Unicode substitution counts codepoints, empty text stays empty';
SET @Ok=CASE WHEN EXISTS(SELECT 1 FROM viz.MeasureText(N'Ae ',18) WHERE Width>30 AND WasSubstituted=0) AND viz.DisplayText(N'A'+NCHAR(10)+N'B')=N'A B' THEN 1 ELSE 0 END;
EXEC #Assert @Ok,N'T03 Whitespace advance and explicit linebreak';
SET @Ok=CASE WHEN viz.FormatNumber(1234.5,'number',2)=N'1234.5' AND viz.FormatNumber(-0.0001,'number',2)=N'0' AND viz.FormatNumber(-1.5,'integer',2)=N'-2' AND viz.FormatNumber(0.125,'percent',2)=N'12.5%' AND viz.FormatNumber(1250,'duration-ms',2)=N'1.25s' AND viz.FormatNumber(1048576,'bytes-iec',2)=N'1MiB' AND viz.FormatNumber(1e15,'compact',2)=N'1P' AND viz.FormatNumber(1,'bogus',2) IS NULL THEN 1 ELSE 0 END;
EXEC #Assert @Ok,N'T04 Number formats and negative rounded zero';
SET @Ok=CASE WHEN viz.FormatTime(0,'utc-datetime')=N'2000-01-01 00:00:00.000 UTC' AND viz.FormatTime(-1,'utc-time')=N'23:59:59' THEN 1 ELSE 0 END;
EXEC #Assert @Ok,N'T04 UTC formatting on both sides of epoch';
SET @Ok=CASE WHEN (SELECT COUNT(*) FROM viz.TextRows(REPLICATE(N'W',400),0,0,18,0))>1 AND NOT EXISTS(SELECT 1 FROM viz.TextRows(REPLICATE(N'W',400),0,0,18,0) WHERE DATALENGTH(Shape.Serialize())>32000) THEN 1 ELSE 0 END;
EXEC #Assert @Ok,N'T06 Long text splits at glyph boundaries within shape budget';
INSERT @Bars VALUES(N'a',N'a',N'Same label',1,N'value',N'Value',1,-5,NULL),(N'b',N'b',N'Zero',2,N'value',N'Value',1,0,NULL),(N'c',N'c',N'Same label',3,N'value',N'Value',1,10,NULL),(N'd',N'd',N'Missing',4,N'value',N'Value',1,NULL,NULL);
INSERT @S EXEC viz.BarChart @Bars,@ValueMin=-5,@ValueMax=10;
SET @Ok=CASE WHEN (SELECT COUNT(*) FROM @S WHERE Kind='mark')=3 AND EXISTS(SELECT 1 FROM @S WHERE Kind='notice' AND Label=N'1 MISSING') AND NOT EXISTS(SELECT 1 FROM @S WHERE Kind='mark' AND ItemKey=N'd') THEN 1 ELSE 0 END;
EXEC #Assert @Ok,N'C01 Missing, duplicate display names and distinct item identities';
DECLARE @AreaA float=(SELECT Shape.STArea() FROM @S WHERE Kind='mark' AND ItemKey=N'a'),@AreaB float=(SELECT Shape.STArea() FROM @S WHERE Kind='mark' AND ItemKey=N'c');
SET @Ok=CASE WHEN ABS(@AreaB/@AreaA-2)<1e-9 AND EXISTS(SELECT 1 FROM @S WHERE Kind='mark' AND ItemKey=N'b' AND Shape.STArea()=0) AND EXISTS(SELECT 1 FROM @S WHERE Kind='text' AND Label=N'0') THEN 1 ELSE 0 END;
EXEC #Assert @Ok,N'C01 Signed bar lengths and geometric zero cross';
INSERT @Again EXEC viz.BarChart @Bars,@ValueMin=-5,@ValueMax=10;
IF EXISTS(SELECT 1 FROM @S a FULL JOIN @Again b ON a.ElementKey=b.ElementKey WHERE a.ElementKey IS NULL OR b.ElementKey IS NULL OR a.Shape.STEquals(b.Shape)=0 OR a.Label<>b.Label) THROW 51998,'Nondeterministic chart.',1;
PRINT 'PASS D05 Repeat produces identical semantic scene';
DELETE @Bars; DELETE @S;
INSERT @S EXEC viz.BarChart @Bars;
SET @Ok=CASE WHEN EXISTS(SELECT 1 FROM @S WHERE Kind='frame') AND EXISTS(SELECT 1 FROM @S WHERE Kind='notice' AND Label=N'NO DATA') THEN 1 ELSE 0 END;
EXEC #Assert @Ok,N'C01 Empty chart retains canvas and geometric NO DATA';
DELETE @S; INSERT @Bars VALUES(N'a',N'a',N'Missing',1,N'value',N'Value',1,NULL,NULL);
INSERT @S EXEC viz.BarChart @Bars;
SET @Ok=CASE WHEN EXISTS(SELECT 1 FROM @S WHERE Kind='notice' AND Label=N'NO DATA - 1 MISSING') THEN 1 ELSE 0 END;
EXEC #Assert @Ok,N'C01 All missing differs from empty';
DELETE @Bars; DELETE @S;
INSERT @Bars SELECT CONVERT(nvarchar(10),N),CONVERT(nvarchar(10),N),CONCAT(N'Category ',N),N,N'value',N'Value',1,N-10,NULL FROM viz.Numbers(20);
INSERT @S EXEC viz.BarChart @Bars;
SET @Ok=CASE WHEN (SELECT COUNT(*) FROM @S WHERE ElementKey LIKE N'category:%')=20 AND (SELECT COUNT(*) FROM @S WHERE Kind='mark')=20 THEN 1 ELSE 0 END;
EXEC #Assert @Ok,N'T07 Twenty labeled bars fit default canvas';
DELETE @Bars; DELETE @S;
INSERT @Bars VALUES(N'a',N'a',REPLICATE(N'Long ',80),1,N'value',N'Value',1,5,NULL);
INSERT @S EXEC viz.BarChart @Bars;
SET @Ok=CASE WHEN EXISTS(SELECT 1 FROM @S WHERE ElementKey LIKE N'category:%' AND DATALENGTH(Label)=800) THEN 1 ELSE 0 END;
EXEC #Assert @Ok,N'T06 Truncated category retains full source Label';
DELETE @S;
INSERT @XY VALUES(N'a1',N'a',N'Alpha',1,1,0,1,NULL,NULL),(N'a2',N'a',N'Alpha',1,2,1,NULL,NULL,NULL),(N'a3',N'a',N'Alpha',1,3,2,3,NULL,NULL),(N'a4',N'a',N'Alpha',1,4,2,4,NULL,NULL),(N'b1',N'b',N'Beta',2,1,1,4,NULL,NULL);
INSERT @S EXEC viz.LineChart @XY,@XMin=0,@XMax=2,@YMin=0,@YMax=5;
SET @Ok=CASE WHEN (SELECT COUNT(*) FROM @S WHERE Kind='mark')=3 AND (SELECT COUNT(*) FROM @S WHERE ElementKey LIKE N'end-label:%')=2 AND NOT EXISTS(SELECT 1 FROM @S WHERE Kind='mark' AND SeriesKey=N'a' AND Shape.STIntersects(viz.Segment(400,80,400,500))=1) THEN 1 ELSE 0 END;
EXEC #Assert @Ok,N'C02 NULL splits line, repeated X is vertical, isolated point has marker';
DELETE @S; DELETE @XY;
INSERT @S EXEC viz.LineChart @XY;
SET @Ok=CASE WHEN EXISTS(SELECT 1 FROM @S WHERE Kind='notice' AND Label=N'NO DATA') THEN 1 ELSE 0 END;
EXEC #Assert @Ok,N'C02 Empty line';
DELETE @S;
INSERT @XY VALUES(N'a',N'q',N'Queries',1,1,0,0,1,NULL),(N'b',N'q',N'Queries',1,2,10,10,4,NULL),(N'c',N'q',N'Queries',1,3,8,7,4,NULL),(N'd',N'q',N'Queries',1,4,4,4,0,NULL),(N'e',N'q',N'Queries',1,5,5,5,NULL,NULL);
INSERT @S EXEC viz.BubbleChart @XY,@XMin=0,@XMax=10,@YMin=0,@YMax=10;
SET @AreaA=(SELECT Shape.STArea() FROM @S WHERE Kind='mark' AND ItemKey=N'a'); SET @AreaB=(SELECT Shape.STArea() FROM @S WHERE Kind='mark' AND ItemKey=N'b');
SET @Ok=CASE WHEN ABS(@AreaB/@AreaA-4)<1e-9 AND ABS(@AreaB-(SELECT Shape.STArea() FROM @S WHERE Kind='mark' AND ItemKey=N'c'))<1e-7 THEN 1 ELSE 0 END;
EXEC #Assert @Ok,N'C03 Independent 1:4 area oracle and equal size equality';
IF EXISTS(SELECT 1 FROM @S CROSS APPLY(SELECT Shape.STEnvelope() E)e CROSS APPLY viz.Numbers(5)n WHERE Kind='mark' AND n.N<e.E.STNumPoints() AND (e.E.STPointN(n.N+1).STX<160-1e-8 OR e.E.STPointN(n.N+1).STX>960+1e-8 OR e.E.STPointN(n.N+1).STY<80-1e-8 OR e.E.STPointN(n.N+1).STY>375+1e-8)) THROW 51998,'Bubble exceeds plot.',1;
PRINT 'PASS C03 Explicit boundary bubbles fit the plot';
SET @Ok=CASE WHEN (SELECT ItemKey FROM @S WHERE ElementKey=N'bubble:1')=N'b' AND EXISTS(SELECT 1 FROM @S WHERE Kind='mark' AND ItemKey=N'd' AND Shape.STArea()=0) AND EXISTS(SELECT 1 FROM @S WHERE Kind='notice' AND Label=N'1 MISSING') AND (SELECT COUNT(*) FROM @S WHERE ElementKey LIKE N'size-circle:%')=3 THEN 1 ELSE 0 END;
EXEC #Assert @Ok,N'C03 Size ordering, zero, missing and three area references';
DELETE @S; UPDATE @XY SET SizeValue=-1;
INSERT @S EXEC viz.BubbleChart @XY,@SizeMode='constant';
SET @Ok=CASE WHEN (SELECT COUNT(*) FROM @S WHERE Kind='mark')=5 AND (SELECT MAX(Shape.STArea())-MIN(Shape.STArea()) FROM @S WHERE Kind='mark')<1e-8 THEN 1 ELSE 0 END;
EXEC #Assert @Ok,N'C03 Scatter ignores even negative size values';
DELETE @S; DELETE @XY;
INSERT @S EXEC viz.BubbleChart @XY;
SET @Ok=CASE WHEN EXISTS(SELECT 1 FROM @S WHERE Kind='notice' AND Label=N'NO DATA') THEN 1 ELSE 0 END;
EXEC #Assert @Ok,N'C03 Empty bubble';
DELETE @S; INSERT @XY VALUES(N'a',N'q',N'Q',1,1,2,3,1,NULL);
INSERT @S EXEC viz.BubbleChart @XY,@XScale='log',@YScale='log';
SET @Ok=CASE WHEN EXISTS(SELECT 1 FROM @S WHERE Kind='mark') AND EXISTS(SELECT 1 FROM @S WHERE Label LIKE N'%log10%') THEN 1 ELSE 0 END;
EXEC #Assert @Ok,N'C03 Constant positive log domains and explicit scale names';
DECLARE @V viz.Vertex_v1;
DECLARE @P TABLE(PartOrder int,FirstVertex int,LastVertex int,Shape geometry);
INSERT @V SELECT 0,N,100+N*0.14,200+SIN(N/20.0)*50 FROM viz.Numbers(5000);
INSERT @P SELECT * FROM viz.LineParts(@V);
IF (SELECT MIN(FirstVertex) FROM @P)<>0 OR (SELECT MAX(LastVertex) FROM @P)<>4999 OR EXISTS(SELECT 1 FROM(SELECT FirstVertex,LAG(LastVertex) OVER(ORDER BY PartOrder) Prev FROM @P)p WHERE Prev<>FirstVertex) OR EXISTS(SELECT 1 FROM @P WHERE DATALENGTH(Shape.Serialize())>32000) THROW 51998,'Line chunk continuity failed.',1;
IF EXISTS(SELECT 1 FROM @V v WHERE NOT EXISTS(SELECT 1 FROM @P p WHERE v.VertexOrder BETWEEN p.FirstVertex AND p.LastVertex AND p.Shape.STDistance(viz.Point(v.X,v.Y))<0.01)) THROW 51998,'Line chunk lost a vertex.',1;
PRINT 'PASS C02/R03 5000 line vertices retained in connected budgeted parts';
DELETE @S; DELETE @XY;
INSERT @XY SELECT CONCAT(N's',N),CONCAT(N's',N),CONCAT(N'Series ',N),N,1,1,1,NULL,NULL FROM viz.Numbers(8);
INSERT @S EXEC viz.LineChart @XY;
SET @Ok=CASE WHEN (SELECT COUNT(*) FROM @S WHERE ElementKey LIKE N'end-label:%')=8 THEN 1 ELSE 0 END;
EXEC #Assert @Ok,N'C02 Eight coincident end labels are centered and staggered';
DELETE @S; DELETE @XY;
INSERT @XY VALUES(N'a',N'q',N'Q',1,1,0.1,0.2,1,NULL),(N'b',N'q',N'Q',1,2,100,200,4,NULL);
INSERT @S EXEC viz.BubbleChart @XY,@XScale='log',@YScale='log';
SET @Ok=CASE WHEN (SELECT COUNT(*) FROM @S WHERE Kind='mark')=2 THEN 1 ELSE 0 END;
EXEC #Assert @Ok,N'C03 Nonconstant sub-unit log padding stays floating point';
DECLARE @OtherSource TABLE(Id nvarchar(200),Executions float,AverageCost float);
INSERT @OtherSource VALUES(N'a',0.1,0.2),(N'b',100,200);
DECLARE @Other viz.XY_v1;
INSERT @Other SELECT Id,N'q',N'Q',1,ROW_NUMBER() OVER(ORDER BY Id),Executions,AverageCost,CASE Id WHEN N'a' THEN 1 ELSE 4 END,NULL FROM @OtherSource;
DELETE @Again; INSERT @Again EXEC viz.BubbleChart @Other,@XScale='log',@YScale='log';
IF EXISTS(SELECT 1 FROM @S a FULL JOIN @Again b ON a.ElementKey=b.ElementKey WHERE a.ElementKey IS NULL OR b.ElementKey IS NULL OR a.Shape.STEquals(b.Shape)=0) THROW 51998,'Source-specific chart behavior.',1;
PRINT 'PASS A01 Two independent synthetic sources produce the same bubble scene';
INSERT @S VALUES(30,9999,N'custom-primitive','mark',NULL,NULL,N'Primitive',viz.Circle(850,300,5)),(30,10000,N'custom-independent','mark',NULL,NULL,N'Independent',geometry::STGeomFromText('POLYGON((800 250,810 270,820 250,800 250))',0));
DELETE @Again; INSERT @Again EXEC viz.RenderScene @S;
SET @Ok=CASE WHEN EXISTS(SELECT 1 FROM @Again WHERE ElementKey=N'custom-independent') AND EXISTS(SELECT 1 FROM @Again WHERE ElementKey=N'custom-primitive') THEN 1 ELSE 0 END;
EXEC #Assert @Ok,N'A02 Captured chart composes with primitive and independent geometry';
IF EXISTS(SELECT 1 FROM sys.sql_expression_dependencies WHERE OBJECT_SCHEMA_NAME(referencing_id)='viz' AND is_ambiguous=0 AND (referenced_schema_name NOT IN('viz') OR referenced_database_name IS NOT NULL OR referenced_server_name IS NOT NULL)) THROW 51998,'Core/chart dependency escapes viz.',1;
PRINT 'PASS A05 No source/DMV/adapter dependencies';
CREATE USER ChartTestUser WITHOUT LOGIN; ALTER ROLE viz_user ADD MEMBER ChartTestUser;
EXECUTE AS USER='ChartTestUser';
DECLARE @UserScene viz.Scene_v1;
INSERT @UserScene EXEC viz.BubbleChart @XY;
SET @G=viz.Text(N'Runtime font',10,10,18,0);
SET @Ok=CASE WHEN @G.STIsValid()=1 AND EXISTS(SELECT 1 FROM @UserScene WHERE Kind='mark') THEN 1 ELSE 0 END;
REVERT; DROP USER ChartTestUser;
EXEC #Assert @Ok,N'I04/A04 Restricted role renders charts and font through ownership chain';
GO
EXEC #Error N'DECLARE @d viz.CategoryValue_v1; EXEC viz.BarChart @d,@Width=319;',51000,N'Invalid canvas';
EXEC #Error N'DECLARE @d viz.CategoryValue_v1,@t nvarchar(max)=REPLICATE(N''x'',101); EXEC viz.BarChart @d,@Title=@t;',51000,N'Oversize title checked before truncation';
EXEC #Error N'DECLARE @d viz.CategoryValue_v1; EXEC viz.BarChart @d,@ValueFormat=''bogus'';',51000,N'Unknown format';
EXEC #Error N'DECLARE @d viz.CategoryValue_v1; EXEC viz.BarChart @d,@ValueMin=1;',51002,N'Partial domain';
EXEC #Error N'DECLARE @d viz.CategoryValue_v1; EXEC viz.BarChart @d,@ValueMin=1,@ValueMax=2;',51002,N'Bar domain excludes baseline';
EXEC #Error N'DECLARE @d viz.CategoryValue_v1; INSERT @d VALUES(N''a'',N''a'',N''A'',1,N''s'',N''S'',1,2,NULL); EXEC viz.BarChart @d,@ValueMin=0,@ValueMax=1;',51002,N'Explicit domain rejects outliers';
EXEC #Error N'DECLARE @d viz.CategoryValue_v1; INSERT @d SELECT CONVERT(nvarchar(10),N),N''same'',N''A'',N,N''s'',N''S'',1,1,NULL FROM viz.Numbers(2); EXEC viz.BarChart @d;',51001,N'Duplicate category identity';
EXEC #Error N'DECLARE @d viz.CategoryValue_v1; INSERT @d SELECT CONVERT(nvarchar(10),N),CONVERT(nvarchar(10),N),N''A'',N,N''s'',N''S'',1,1,NULL FROM viz.Numbers(21); EXEC viz.BarChart @d;',51004,N'No silent Top20';
EXEC #Error N'DECLARE @d viz.XY_v1; INSERT @d VALUES(N''a'',N''s'',N''S'',1,1,2,1,NULL,NULL),(N''b'',N''s'',N''S'',1,2,1,2,NULL,NULL); EXEC viz.LineChart @d;',51001,N'Decreasing X rejected';
EXEC #Error N'DECLARE @d viz.XY_v1; INSERT @d VALUES(N''a'',N''s'',N''S'',1,1,1,1,NULL,NULL),(N''b'',N''s'',N''S'',1,1,2,2,NULL,NULL); EXEC viz.LineChart @d;',51001,N'Duplicate PointOrder rejected';
EXEC #Error N'DECLARE @d viz.XY_v1; INSERT @d VALUES(N''a'',N''s'',N''S'',1,1,1,1,NULL,NULL),(N''b'',N''s'',N''different'',1,2,2,2,NULL,NULL); EXEC viz.LineChart @d;',51001,N'Conflicting series metadata';
EXEC #Error N'DECLARE @d viz.XY_v1; INSERT @d VALUES(N''a'',N''s'',N''S'',1,1,0.1,1,NULL,NULL); EXEC viz.LineChart @d,@XKind=''time'',@XFormat=''utc-time'';',51002,N'Fractional UTC millisecond rejected';
EXEC #Error N'DECLARE @d viz.XY_v1; EXEC viz.LineChart @d,@XKind=''time'';',51000,N'Time format must be explicit';
EXEC #Error N'DECLARE @d viz.XY_v1; INSERT @d VALUES(N''a'',N''s'',N''S'',1,1,1,1,-1,NULL); EXEC viz.BubbleChart @d;',51001,N'Negative area rejected';
EXEC #Error N'DECLARE @d viz.XY_v1; INSERT @d VALUES(N''a'',N''s'',N''S'',1,1,0,1,1,NULL); EXEC viz.BubbleChart @d,@XScale=''log'';',51002,N'Nonpositive log X rejected';
EXEC #Error N'DECLARE @d viz.XY_v1; INSERT @d SELECT CONVERT(nvarchar(10),N),N''s'',N''S'',1,N,N,1,1,NULL FROM viz.Numbers(201); EXEC viz.BubbleChart @d;',51004,N'No silent bubble downsampling';
EXEC #Error N'DECLARE @d viz.XY_v1; INSERT @d SELECT CONVERT(nvarchar(10),N),N''s'',N''S'',1,N,N,1,1,NULL FROM viz.Numbers(5001); EXEC viz.LineChart @d;',51004,N'No silent line downsampling';
EXEC #Error N'DECLARE @d viz.XY_v1; INSERT @d VALUES(N''a'',N''s'',N''S'',1,1,1e16,1,1,NULL); EXEC viz.LineChart @d;',51004,N'Input numeric budget';
EXEC #Error N'DECLARE @d viz.XY_v1; EXEC viz.LineChart @d,@XMin=0,@XMax=0.000000001;',51000,N'Indistinguishable ticks fail explicitly';
EXEC #Error N'DECLARE @d viz.XY_v1; INSERT @d SELECT CONVERT(nvarchar(10),N),CONVERT(nvarchar(10),N),N''S'',N,1,N,N,1,NULL FROM viz.Numbers(9); EXEC viz.BubbleChart @d;',51004,N'Eight-series budget';
EXEC #Error N'DECLARE @d viz.XY_v1; INSERT @d VALUES(N''a'',N''s'',N''S'',1,1,1,1,1e-100,NULL),(N''b'',N''s'',N''S'',1,2,2,2,1e15,NULL); EXEC viz.BubbleChart @d;',51004,N'Unrepresentable positive bubble radius is explicit';
EXEC #Error N'DECLARE @d viz.CategoryValue_v1; INSERT @d VALUES(N''a'',N''a'',N''A'',1,N''s'',N''S'',1,1e-100,NULL); EXEC viz.BarChart @d,@ValueMin=0,@ValueMax=1e15;',51004,N'Unrepresentable nonzero bar width is explicit';
PRINT 'PASS ALL S3/S4 CONTRACTS';
