#requires -Version 7.0
[CmdletBinding()]
param()
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$root=Split-Path $PSScriptRoot -Parent
$manifest=Get-Content (Join-Path $root 'src/core/manifest.json') -Raw | ConvertFrom-Json
function Quote-Sql([string] $text) { return "N'"+$text.Replace("'","''")+"'" }
$sql=[Text.StringBuilder]::new()
[void]$sql.AppendLine(@'
-- Generated by tools/build.ps1. Execute the complete script in the selected user database.
-- One batch: nested DDL is compiled inside the transaction and caught on failure.
SET NOCOUNT ON;
SET XACT_ABORT ON;
IF @@TRANCOUNT<>0 THROW 51001,'Run the installer outside an existing transaction.',1;
IF DB_ID()<=4 THROW 51001,'Install into a user database.',1;
IF CONVERT(int,SERVERPROPERTY('ProductMajorVersion'))<14 OR
   (SELECT compatibility_level FROM sys.databases WHERE database_id=DB_ID())<140
    THROW 51001,'Core requires SQL Server 2017 and compatibility level 140 or newer.',1;
DECLARE @Expected TABLE(Name sysname COLLATE Latin1_General_100_BIN2 PRIMARY KEY,Kind varchar(12),SourceHash varchar(64));
'@)
foreach($o in $manifest.objects) {
    $hash=(Get-FileHash (Join-Path $root $o.path) -Algorithm SHA256).Hash
    [void]$sql.AppendLine("INSERT @Expected VALUES($(Quote-Sql $o.name),$(Quote-Sql $o.kind),'$hash');")
}
[void]$sql.AppendLine(@'
BEGIN TRY
    BEGIN TRANSACTION;
    DECLARE @Lock int;
    EXEC @Lock=sys.sp_getapplock @Resource=N'TSQLViz.Core.Install',@LockMode='Exclusive',@LockOwner='Transaction',@LockTimeout=10000;
    IF @Lock<0 THROW 51001,'Could not acquire the Core installation lock.',1;
    DECLARE @Existing TABLE(Name sysname COLLATE Latin1_General_100_BIN2,Kind varchar(12),Id int,Class int);
    INSERT @Existing SELECT name,CASE type WHEN 'U' THEN 'TABLE' WHEN 'FN' THEN 'FUNCTION' WHEN 'FS' THEN 'FUNCTION' WHEN 'IF' THEN 'TVF' WHEN 'TF' THEN 'TVF' WHEN 'P' THEN 'PROCEDURE' ELSE type END,object_id,1
    FROM sys.objects o WHERE schema_id=SCHEMA_ID('viz') AND parent_object_id=0 AND type<>'TT'
      AND NOT(name COLLATE Latin1_General_100_BIN2 IN('BarChart','LineChart','BubbleChart') AND type='P' AND EXISTS(SELECT 1 FROM sys.extended_properties p WHERE p.class=1 AND p.major_id=o.object_id AND p.minor_id=0 AND p.name=N'TSQLViz.Owner' AND CONVERT(nvarchar(100),p.value)=N'charts-v1'));
    INSERT @Existing SELECT name,'TYPE',user_type_id,6 FROM sys.types WHERE schema_id=SCHEMA_ID('viz') AND is_user_defined=1;
    DECLARE @Collision nvarchar(2048);
    SELECT @Collision=LEFT(STRING_AGG(CONVERT(nvarchar(max),x.Name),N', '),1900)
    FROM @Existing x LEFT JOIN @Expected e ON x.Name=e.Name AND x.Kind=e.Kind
    WHERE e.Name IS NULL OR NOT EXISTS(SELECT 1 FROM sys.extended_properties p WHERE p.class=x.Class AND p.major_id=x.Id AND p.minor_id=0 AND p.name=N'TSQLViz.Owner' AND CONVERT(nvarchar(100),p.value)=N'core-v1');
    IF @Collision IS NOT NULL BEGIN
        SET @Collision=N'Foreign or incompatible objects in viz: '+@Collision;
        THROW 51001,@Collision,1;
    END;
    IF SCHEMA_ID('viz') IS NOT NULL AND (SELECT principal_id FROM sys.schemas WHERE name='viz')<>DATABASE_PRINCIPAL_ID('dbo')
        THROW 51001,'The viz schema must be owned by dbo for the tested ownership chain.',1;
    IF EXISTS(SELECT 1 FROM @Existing) AND OBJECT_ID('viz.ObjectManifest','U') IS NULL
        THROW 51001,'Existing Core objects have no installation manifest.',1;
    IF DATABASE_PRINCIPAL_ID('viz_user') IS NOT NULL BEGIN
        IF OBJECT_ID('viz.ObjectManifest','U') IS NULL THROW 51001,'Foreign principal viz_user.',1;
        EXEC sys.sp_executesql N'IF NOT EXISTS(SELECT 1 FROM viz.ObjectManifest WHERE ObjectName=N''@role:viz_user'' AND ObjectKind=''ROLE'') THROW 51001,''Foreign principal viz_user.'',1;';
        IF NOT EXISTS(SELECT 1 FROM sys.database_principals WHERE name='viz_user' AND type='R' AND owning_principal_id=DATABASE_PRINCIPAL_ID('dbo'))
            THROW 51001,'Incompatible viz_user role.',1;
    END;
    -- Structural signatures protect immutable types and persisted tables from silent drift.
    DECLARE @Name sysname,@Kind varchar(12),@CatalogId int,@CatalogHash varbinary(32),@StoredHash varbinary(32),@Shape nvarchar(max),@InstalledSource varchar(64),@ExpectedSource varchar(64);
    DECLARE check_objects CURSOR LOCAL FAST_FORWARD FOR SELECT Name,Kind FROM @Existing WHERE Kind IN ('TYPE','TABLE');
    OPEN check_objects;
    FETCH NEXT FROM check_objects INTO @Name,@Kind;
    WHILE @@FETCH_STATUS=0 BEGIN
        SET @CatalogId=CASE WHEN @Kind='TYPE' THEN (SELECT type_table_object_id FROM sys.table_types WHERE schema_id=SCHEMA_ID('viz') AND name=@Name) ELSE OBJECT_ID(N'viz.'+QUOTENAME(@Name)) END;
        SET @Shape=(SELECT column_id,name,system_type_id,user_type_id,max_length,precision,scale,collation_name,is_nullable,is_identity FROM sys.columns WHERE object_id=@CatalogId ORDER BY column_id FOR XML RAW);
        SET @Shape=@Shape+(SELECT i.index_id,i.is_unique,i.is_primary_key,c.column_id,c.key_ordinal,c.is_descending_key FROM sys.indexes i JOIN sys.index_columns c ON c.object_id=i.object_id AND c.index_id=i.index_id WHERE i.object_id=@CatalogId ORDER BY i.index_id,c.index_column_id FOR XML RAW);
        SET @Shape=@Shape+COALESCE((SELECT definition FROM sys.check_constraints WHERE parent_object_id=@CatalogId ORDER BY definition FOR XML RAW),N'');
        SET @CatalogHash=HASHBYTES('SHA2_256',@Shape); SET @StoredHash=NULL;
        EXEC sys.sp_executesql N'SELECT @h=CatalogHash FROM viz.ObjectManifest WHERE ObjectName=@n;',N'@n sysname,@h varbinary(32) OUTPUT',@Name,@StoredHash OUTPUT;
        IF @StoredHash IS NULL OR @StoredHash<>@CatalogHash THROW 51001,'Core table/type structure differs from the installed manifest.',1;
        SET @InstalledSource=NULL;
        SELECT @ExpectedSource=SourceHash FROM @Expected WHERE Name=@Name;
        EXEC sys.sp_executesql N'SELECT @s=SourceHash FROM viz.ObjectManifest WHERE ObjectName=@n;',N'@n sysname,@s varchar(64) OUTPUT',@Name,@InstalledSource OUTPUT;
        IF @InstalledSource IS NULL OR @InstalledSource<>@ExpectedSource THROW 51001,'Changed table/type source requires an explicit versioned migration.',1;
        FETCH NEXT FROM check_objects INTO @Name,@Kind;
    END;
    CLOSE check_objects; DEALLOCATE check_objects;
    IF SCHEMA_ID('viz') IS NULL EXEC(N'CREATE SCHEMA viz AUTHORIZATION dbo;');
'@)
[void]$sql.AppendLine("IF OBJECT_ID('viz.LibraryVersion','U') IS NOT NULL EXEC(N'IF EXISTS(SELECT 1 FROM viz.LibraryVersion WHERE Version NOT IN(''0.1.0-s2'',''$($manifest.version)'')) THROW 51001,''Supported migration: 0.1.0-s2 to 0.1.0-s4; otherwise clean or same-version install required.'',1;');")
foreach($o in $manifest.objects) {
    $body=Get-Content (Join-Path $root $o.path) -Raw
    $guard=if($o.kind -eq 'TYPE') { "IF TYPE_ID(N'viz.$($o.name)') IS NULL " } elseif($o.kind -eq 'TABLE') { "IF OBJECT_ID(N'viz.$($o.name)',N'U') IS NULL " } else { '' }
    [void]$sql.AppendLine("-- $($o.path)`n${guard}EXEC sys.sp_executesql $(Quote-Sql $body);")
    $level=if($o.kind -eq 'TYPE') {'TYPE'} elseif($o.kind -eq 'TVF') {'FUNCTION'} else {$o.kind}
    $class=if($o.kind -eq 'TYPE') {6} else {1}
    $id=if($o.kind -eq 'TYPE') {"TYPE_ID(N'viz.$($o.name)')"} else {"OBJECT_ID(N'viz.$($o.name)')"}
    [void]$sql.AppendLine("IF NOT EXISTS(SELECT 1 FROM sys.extended_properties WHERE class=$class AND major_id=$id AND minor_id=0 AND name=N'TSQLViz.Owner') EXEC sys.sp_addextendedproperty @name=N'TSQLViz.Owner',@value=N'core-v1',@level0type=N'SCHEMA',@level0name=N'viz',@level1type=N'$level',@level1name=$(Quote-Sql $o.name);")
}
foreach($dataPath in $manifest.data) {
    [void]$sql.AppendLine("-- $dataPath`nEXEC sys.sp_executesql $(Quote-Sql (Get-Content (Join-Path $root $dataPath) -Raw));")
}
[void]$sql.AppendLine("IF DATABASE_PRINCIPAL_ID('viz_user') IS NULL CREATE ROLE viz_user AUTHORIZATION dbo;")
foreach($o in $manifest.objects | Where-Object public) {
    $grant=switch($o.kind) {'TYPE' {"EXECUTE, REFERENCES ON TYPE::viz.[$($o.name)]"} 'TVF' {"SELECT ON OBJECT::viz.[$($o.name)]"} default {"EXECUTE ON OBJECT::viz.[$($o.name)]"} }
    [void]$sql.AppendLine("GRANT $grant TO viz_user;")
}
[void]$sql.AppendLine(@'
    EXEC sys.sp_executesql N'DELETE FROM viz.ObjectManifest WHERE ObjectName NOT LIKE N''charts:%'';';
    DECLARE @SourceHash varchar(64);
    DECLARE save_objects CURSOR LOCAL FAST_FORWARD FOR SELECT Name,Kind,SourceHash FROM @Expected;
    OPEN save_objects;
    FETCH NEXT FROM save_objects INTO @Name,@Kind,@SourceHash;
    WHILE @@FETCH_STATUS=0 BEGIN
        SET @CatalogHash=NULL;
        IF @Kind IN ('TABLE','TYPE') BEGIN
            SET @CatalogId=CASE WHEN @Kind='TYPE' THEN (SELECT type_table_object_id FROM sys.table_types WHERE schema_id=SCHEMA_ID('viz') AND name=@Name) ELSE OBJECT_ID(N'viz.'+QUOTENAME(@Name)) END;
            SET @Shape=(SELECT column_id,name,system_type_id,user_type_id,max_length,precision,scale,collation_name,is_nullable,is_identity FROM sys.columns WHERE object_id=@CatalogId ORDER BY column_id FOR XML RAW);
            SET @Shape=@Shape+(SELECT i.index_id,i.is_unique,i.is_primary_key,c.column_id,c.key_ordinal,c.is_descending_key FROM sys.indexes i JOIN sys.index_columns c ON c.object_id=i.object_id AND c.index_id=i.index_id WHERE i.object_id=@CatalogId ORDER BY i.index_id,c.index_column_id FOR XML RAW);
            SET @Shape=@Shape+COALESCE((SELECT definition FROM sys.check_constraints WHERE parent_object_id=@CatalogId ORDER BY definition FOR XML RAW),N'');
            SET @CatalogHash=HASHBYTES('SHA2_256',@Shape);
        END;
        EXEC sys.sp_executesql N'INSERT viz.ObjectManifest VALUES(@n,@k,@s,@h);',N'@n sysname,@k varchar(12),@s varchar(64),@h varbinary(32)',@Name,@Kind,@SourceHash,@CatalogHash;
        FETCH NEXT FROM save_objects INTO @Name,@Kind,@SourceHash;
    END;
    CLOSE save_objects; DEALLOCATE save_objects;
    EXEC sys.sp_executesql N'INSERT viz.ObjectManifest VALUES(N''@role:viz_user'',''ROLE'','''',NULL);';
'@)
[void]$sql.AppendLine("EXEC sys.sp_executesql N'IF NOT EXISTS(SELECT 1 FROM viz.LibraryVersion) INSERT viz.LibraryVersion VALUES(1,''$($manifest.version)'',SYSUTCDATETIME()); ELSE UPDATE viz.LibraryVersion SET Version=''$($manifest.version)'' WHERE Version<>''$($manifest.version)'';';")
[void]$sql.AppendLine(@'
    COMMIT;
END TRY
BEGIN CATCH
    IF XACT_STATE()<>0 ROLLBACK;
    THROW;
END CATCH;
'@)
[void](New-Item -ItemType Directory (Join-Path $root 'dist') -Force)
[IO.File]::WriteAllText((Join-Path $root 'dist/install-core.sql'),$sql.ToString().Replace("`r`n","`n"),[Text.UTF8Encoding]::new($false))
Write-Output "Built dist/install-core.sql ($($manifest.objects.Count) objects, version $($manifest.version))."

$remove=[Text.StringBuilder]::new()
[void]$remove.AppendLine(@'
-- Generated Core-only uninstall. Refuses external dependencies and role members.
SET NOCOUNT ON;
SET XACT_ABORT ON;
IF @@TRANCOUNT<>0 THROW 51001,'Run the uninstaller outside an existing transaction.',1;
IF DB_ID()<=4 THROW 51001,'Select a user database.',1;
BEGIN TRY
 BEGIN TRANSACTION;
 DECLARE @Lock int;
 EXEC @Lock=sys.sp_getapplock @Resource=N'TSQLViz.Core.Install',@LockMode='Exclusive',@LockOwner='Transaction',@LockTimeout=10000;
 IF @Lock<0 THROW 51001,'Could not acquire the Core installation lock.',1;
 IF OBJECT_ID('viz.ObjectManifest','U') IS NULL THROW 51001,'Core manifest is missing; nothing removed.',1;
 IF NOT EXISTS(SELECT 1 FROM sys.extended_properties WHERE class=1 AND major_id=OBJECT_ID('viz.ObjectManifest') AND name=N'TSQLViz.Owner' AND CONVERT(nvarchar(100),value)=N'core-v1')
  THROW 51001,'Core manifest ownership is missing.',1;
 IF EXISTS(SELECT 1 FROM sys.database_role_members WHERE role_principal_id=DATABASE_PRINCIPAL_ID('viz_user'))
  THROW 51001,'Remove viz_user role members before uninstalling Core.',1;
 DECLARE @Owned TABLE(Id int,Class int);
 INSERT @Owned SELECT object_id,1 FROM sys.objects o WHERE schema_id=SCHEMA_ID('viz') AND parent_object_id=0 AND type<>'TT';
 INSERT @Owned SELECT user_type_id,6 FROM sys.types WHERE schema_id=SCHEMA_ID('viz') AND is_user_defined=1;
 IF EXISTS(SELECT 1 FROM @Owned o WHERE NOT EXISTS(SELECT 1 FROM sys.extended_properties p WHERE p.class=o.Class AND p.major_id=o.Id AND p.minor_id=0 AND p.name=N'TSQLViz.Owner' AND CONVERT(nvarchar(100),p.value)=N'core-v1'))
  THROW 51001,'Foreign objects in viz; nothing removed.',1;
 IF EXISTS(SELECT 1 FROM sys.sql_expression_dependencies d JOIN @Owned o ON d.referenced_id=o.Id AND d.referenced_class=o.Class
   WHERE NOT EXISTS(SELECT 1 FROM @Owned x WHERE x.Class=1 AND x.Id=d.referencing_id)
   AND NOT EXISTS(SELECT 1 FROM sys.objects p JOIN @Owned x ON p.parent_object_id=x.Id AND x.Class=1 WHERE p.object_id=d.referencing_id))
  THROW 51001,'External SQL dependencies on Core; nothing removed.',1;
 IF EXISTS(SELECT 1 FROM sys.parameters p JOIN @Owned o ON o.Class=6 AND o.Id=p.user_type_id WHERE NOT EXISTS(SELECT 1 FROM @Owned x WHERE x.Class=1 AND x.Id=p.object_id))
  THROW 51001,'External type dependencies on Core; nothing removed.',1;
 IF EXISTS(SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id IN(SELECT Id FROM @Owned WHERE Class=1) AND parent_object_id NOT IN(SELECT Id FROM @Owned WHERE Class=1))
  THROW 51001,'External foreign keys reference Core; nothing removed.',1;
'@)
for($i=$manifest.objects.Count-1;$i -ge 0;$i--) {
    $o=$manifest.objects[$i]
    $kind=if($o.kind -eq 'TVF') {'FUNCTION'} else {$o.kind}
    # Refuse manifest tampering or a different package before each drop. The transaction
    # restores earlier drops if a late ownership check or engine dependency fails.
    [void]$remove.AppendLine("EXEC sys.sp_executesql N'IF NOT EXISTS(SELECT 1 FROM viz.ObjectManifest WHERE ObjectName=N''$($o.name)'' AND ObjectKind=''$($o.kind)'') THROW 51001,''Unexpected Core manifest.'',1;';")
    # Retain the manifest until every other object has been validated and dropped.
    if($o.name -ne 'ObjectManifest') { [void]$remove.AppendLine("EXEC(N'DROP $kind viz.[$($o.name)];');") }
}
[void]$remove.AppendLine(@'
 EXEC sys.sp_executesql N'IF NOT EXISTS(SELECT 1 FROM viz.ObjectManifest WHERE ObjectName=N''@role:viz_user'' AND ObjectKind=''ROLE'') THROW 51001,''Role is not owned by Core.'',1;';
 DROP ROLE viz_user;
 EXEC(N'DROP TABLE viz.ObjectManifest;');
 -- Preserve the schema itself: it may predate this installation.
 COMMIT;
END TRY
BEGIN CATCH
 IF XACT_STATE()<>0 ROLLBACK;
 THROW;
END CATCH;
'@)
[IO.File]::WriteAllText((Join-Path $root 'dist/uninstall-core.sql'),$remove.ToString().Replace("`r`n","`n"),[Text.UTF8Encoding]::new($false))
